/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.api

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import ai.hanzo.cloud.model.AiEnvelope
import ai.hanzo.cloud.model.AiError

import com.google.gson.annotations.SerializedName

import ai.hanzo.cloud.infrastructure.ApiClient
import ai.hanzo.cloud.infrastructure.ApiResponse
import ai.hanzo.cloud.infrastructure.ClientException
import ai.hanzo.cloud.infrastructure.ClientError
import ai.hanzo.cloud.infrastructure.ServerException
import ai.hanzo.cloud.infrastructure.ServerError
import ai.hanzo.cloud.infrastructure.MultiValueMap
import ai.hanzo.cloud.infrastructure.PartConfig
import ai.hanzo.cloud.infrastructure.RequestConfig
import ai.hanzo.cloud.infrastructure.RequestMethod
import ai.hanzo.cloud.infrastructure.ResponseType
import ai.hanzo.cloud.infrastructure.Success
import ai.hanzo.cloud.infrastructure.toMultiValue

class ArticlesApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "https://api.hanzo.ai")
        }
    }

    /**
     * POST /v1/ai/articles
     * Create a article
     * Create one article.
     * @param body 
     * @return AiEnvelope
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun aiAddArticle(body: kotlin.Any) : AiEnvelope {
        val localVarResponse = aiAddArticleWithHttpInfo(body = body)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as AiEnvelope
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/ai/articles
     * Create a article
     * Create one article.
     * @param body 
     * @return ApiResponse<AiEnvelope?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun aiAddArticleWithHttpInfo(body: kotlin.Any) : ApiResponse<AiEnvelope?> {
        val localVariableConfig = aiAddArticleRequestConfig(body = body)

        return request<kotlin.Any, AiEnvelope>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation aiAddArticle
     *
     * @param body 
     * @return RequestConfig
     */
    fun aiAddArticleRequestConfig(body: kotlin.Any) : RequestConfig<kotlin.Any> {
        val localVariableBody = body
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/ai/articles",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /v1/ai/articles/{owner}/{name}
     * Delete a article
     * Delete one article.
     * @param owner Owning organization.
     * @param name Resource name, unique within the owner.
     * @return AiEnvelope
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun aiDeleteArticle(owner: kotlin.String, name: kotlin.String) : AiEnvelope {
        val localVarResponse = aiDeleteArticleWithHttpInfo(owner = owner, name = name)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as AiEnvelope
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /v1/ai/articles/{owner}/{name}
     * Delete a article
     * Delete one article.
     * @param owner Owning organization.
     * @param name Resource name, unique within the owner.
     * @return ApiResponse<AiEnvelope?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun aiDeleteArticleWithHttpInfo(owner: kotlin.String, name: kotlin.String) : ApiResponse<AiEnvelope?> {
        val localVariableConfig = aiDeleteArticleRequestConfig(owner = owner, name = name)

        return request<Unit, AiEnvelope>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation aiDeleteArticle
     *
     * @param owner Owning organization.
     * @param name Resource name, unique within the owner.
     * @return RequestConfig
     */
    fun aiDeleteArticleRequestConfig(owner: kotlin.String, name: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/v1/ai/articles/{owner}/{name}".replace("{"+"owner"+"}", encodeURIComponent(owner.toString())).replace("{"+"name"+"}", encodeURIComponent(name.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/ai/articles/{owner}/{name}
     * Retrieve a article
     * Read one article by its (owner, name) key.
     * @param owner Owning organization.
     * @param name Resource name, unique within the owner.
     * @return AiEnvelope
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun aiGetArticle(owner: kotlin.String, name: kotlin.String) : AiEnvelope {
        val localVarResponse = aiGetArticleWithHttpInfo(owner = owner, name = name)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as AiEnvelope
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/ai/articles/{owner}/{name}
     * Retrieve a article
     * Read one article by its (owner, name) key.
     * @param owner Owning organization.
     * @param name Resource name, unique within the owner.
     * @return ApiResponse<AiEnvelope?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun aiGetArticleWithHttpInfo(owner: kotlin.String, name: kotlin.String) : ApiResponse<AiEnvelope?> {
        val localVariableConfig = aiGetArticleRequestConfig(owner = owner, name = name)

        return request<Unit, AiEnvelope>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation aiGetArticle
     *
     * @param owner Owning organization.
     * @param name Resource name, unique within the owner.
     * @return RequestConfig
     */
    fun aiGetArticleRequestConfig(owner: kotlin.String, name: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/ai/articles/{owner}/{name}".replace("{"+"owner"+"}", encodeURIComponent(owner.toString())).replace("{"+"name"+"}", encodeURIComponent(name.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/ai/articles
     * List articles
     * List the caller&#39;s articles.
     * @return AiEnvelope
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun aiGetArticles() : AiEnvelope {
        val localVarResponse = aiGetArticlesWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as AiEnvelope
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/ai/articles
     * List articles
     * List the caller&#39;s articles.
     * @return ApiResponse<AiEnvelope?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun aiGetArticlesWithHttpInfo() : ApiResponse<AiEnvelope?> {
        val localVariableConfig = aiGetArticlesRequestConfig()

        return request<Unit, AiEnvelope>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation aiGetArticles
     *
     * @return RequestConfig
     */
    fun aiGetArticlesRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/ai/articles",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/ai/articles/global
     * List articles across tenants
     * Cross-tenant listing. Admin-only; a tenant caller is refused.
     * @return AiEnvelope
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun aiGetGlobalArticles() : AiEnvelope {
        val localVarResponse = aiGetGlobalArticlesWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as AiEnvelope
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/ai/articles/global
     * List articles across tenants
     * Cross-tenant listing. Admin-only; a tenant caller is refused.
     * @return ApiResponse<AiEnvelope?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun aiGetGlobalArticlesWithHttpInfo() : ApiResponse<AiEnvelope?> {
        val localVariableConfig = aiGetGlobalArticlesRequestConfig()

        return request<Unit, AiEnvelope>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation aiGetGlobalArticles
     *
     * @return RequestConfig
     */
    fun aiGetGlobalArticlesRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/ai/articles/global",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /v1/ai/articles/{owner}/{name}
     * Replace a article
     * Identical to PATCH — the handler takes a whole object either way.
     * @param owner Owning organization.
     * @param name Resource name, unique within the owner.
     * @param body 
     * @return AiEnvelope
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun aiReplaceArticle(owner: kotlin.String, name: kotlin.String, body: kotlin.Any) : AiEnvelope {
        val localVarResponse = aiReplaceArticleWithHttpInfo(owner = owner, name = name, body = body)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as AiEnvelope
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /v1/ai/articles/{owner}/{name}
     * Replace a article
     * Identical to PATCH — the handler takes a whole object either way.
     * @param owner Owning organization.
     * @param name Resource name, unique within the owner.
     * @param body 
     * @return ApiResponse<AiEnvelope?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun aiReplaceArticleWithHttpInfo(owner: kotlin.String, name: kotlin.String, body: kotlin.Any) : ApiResponse<AiEnvelope?> {
        val localVariableConfig = aiReplaceArticleRequestConfig(owner = owner, name = name, body = body)

        return request<kotlin.Any, AiEnvelope>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation aiReplaceArticle
     *
     * @param owner Owning organization.
     * @param name Resource name, unique within the owner.
     * @param body 
     * @return RequestConfig
     */
    fun aiReplaceArticleRequestConfig(owner: kotlin.String, name: kotlin.String, body: kotlin.Any) : RequestConfig<kotlin.Any> {
        val localVariableBody = body
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/v1/ai/articles/{owner}/{name}".replace("{"+"owner"+"}", encodeURIComponent(owner.toString())).replace("{"+"name"+"}", encodeURIComponent(name.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PATCH /v1/ai/articles/{owner}/{name}
     * Update a article
     * Update one article. PATCH and PUT reach the same handler, which has always taken a whole object.
     * @param owner Owning organization.
     * @param name Resource name, unique within the owner.
     * @param body 
     * @return AiEnvelope
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun aiUpdateArticle(owner: kotlin.String, name: kotlin.String, body: kotlin.Any) : AiEnvelope {
        val localVarResponse = aiUpdateArticleWithHttpInfo(owner = owner, name = name, body = body)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as AiEnvelope
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PATCH /v1/ai/articles/{owner}/{name}
     * Update a article
     * Update one article. PATCH and PUT reach the same handler, which has always taken a whole object.
     * @param owner Owning organization.
     * @param name Resource name, unique within the owner.
     * @param body 
     * @return ApiResponse<AiEnvelope?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun aiUpdateArticleWithHttpInfo(owner: kotlin.String, name: kotlin.String, body: kotlin.Any) : ApiResponse<AiEnvelope?> {
        val localVariableConfig = aiUpdateArticleRequestConfig(owner = owner, name = name, body = body)

        return request<kotlin.Any, AiEnvelope>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation aiUpdateArticle
     *
     * @param owner Owning organization.
     * @param name Resource name, unique within the owner.
     * @param body 
     * @return RequestConfig
     */
    fun aiUpdateArticleRequestConfig(owner: kotlin.String, name: kotlin.String, body: kotlin.Any) : RequestConfig<kotlin.Any> {
        val localVariableBody = body
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/v1/ai/articles/{owner}/{name}".replace("{"+"owner"+"}", encodeURIComponent(owner.toString())).replace("{"+"name"+"}", encodeURIComponent(name.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
