/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.api

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import ai.hanzo.cloud.model.IamApplication
import ai.hanzo.cloud.model.IamCreateOrganizationInput
import ai.hanzo.cloud.model.IamDeleteOrganizationInput
import ai.hanzo.cloud.model.IamDeleteResult
import ai.hanzo.cloud.model.IamInput
import ai.hanzo.cloud.model.IamProvider
import ai.hanzo.cloud.model.IamResponse
import ai.hanzo.cloud.model.IamUpdateOrganizationInput
import ai.hanzo.cloud.model.IamprojectsRef
import ai.hanzo.cloud.model.IamrolesInput
import ai.hanzo.cloud.model.IamrolesRef
import ai.hanzo.cloud.model.IamuserBody
import ai.hanzo.cloud.model.IamworkspacesInput
import ai.hanzo.cloud.model.IamworkspacesRef

import com.google.gson.annotations.SerializedName

import ai.hanzo.cloud.infrastructure.ApiClient
import ai.hanzo.cloud.infrastructure.ApiResponse
import ai.hanzo.cloud.infrastructure.ClientException
import ai.hanzo.cloud.infrastructure.ClientError
import ai.hanzo.cloud.infrastructure.ServerException
import ai.hanzo.cloud.infrastructure.ServerError
import ai.hanzo.cloud.infrastructure.MultiValueMap
import ai.hanzo.cloud.infrastructure.PartConfig
import ai.hanzo.cloud.infrastructure.RequestConfig
import ai.hanzo.cloud.infrastructure.RequestMethod
import ai.hanzo.cloud.infrastructure.ResponseType
import ai.hanzo.cloud.infrastructure.Success
import ai.hanzo.cloud.infrastructure.toMultiValue

class CompatApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "https://api.hanzo.ai")
        }
    }

    /**
     * DELETE /v1/iam/application
     * Removes an application.
     * Removes an application. Anyone mid-sign-in through it is turned away and its client credentials stop working, so retire the integration before deleting it.
     * @param owner 
     * @param name 
     * @return IamDeleteResult
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun deleteIamApplication(owner: kotlin.String, name: kotlin.String) : IamDeleteResult {
        val localVarResponse = deleteIamApplicationWithHttpInfo(owner = owner, name = name)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as IamDeleteResult
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /v1/iam/application
     * Removes an application.
     * Removes an application. Anyone mid-sign-in through it is turned away and its client credentials stop working, so retire the integration before deleting it.
     * @param owner 
     * @param name 
     * @return ApiResponse<IamDeleteResult?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun deleteIamApplicationWithHttpInfo(owner: kotlin.String, name: kotlin.String) : ApiResponse<IamDeleteResult?> {
        val localVariableConfig = deleteIamApplicationRequestConfig(owner = owner, name = name)

        return request<Unit, IamDeleteResult>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation deleteIamApplication
     *
     * @param owner 
     * @param name 
     * @return RequestConfig
     */
    fun deleteIamApplicationRequestConfig(owner: kotlin.String, name: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("owner", listOf(owner.toString()))
                put("name", listOf(name.toString()))
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/v1/iam/application",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/iam/application
     * Returns one application: its sign-in methods, its allowed redirect URIs and the client credentials your integration authenticates with.
     * Returns one application: its sign-in methods, its allowed redirect URIs and the client credentials your integration authenticates with.
     * @param owner 
     * @param name 
     * @return IamApplication
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getIamApplication(owner: kotlin.String, name: kotlin.String) : IamApplication {
        val localVarResponse = getIamApplicationWithHttpInfo(owner = owner, name = name)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as IamApplication
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/iam/application
     * Returns one application: its sign-in methods, its allowed redirect URIs and the client credentials your integration authenticates with.
     * Returns one application: its sign-in methods, its allowed redirect URIs and the client credentials your integration authenticates with.
     * @param owner 
     * @param name 
     * @return ApiResponse<IamApplication?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getIamApplicationWithHttpInfo(owner: kotlin.String, name: kotlin.String) : ApiResponse<IamApplication?> {
        val localVariableConfig = getIamApplicationRequestConfig(owner = owner, name = name)

        return request<Unit, IamApplication>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getIamApplication
     *
     * @param owner 
     * @param name 
     * @return RequestConfig
     */
    fun getIamApplicationRequestConfig(owner: kotlin.String, name: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("owner", listOf(owner.toString()))
                put("name", listOf(name.toString()))
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/iam/application",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * POST /v1/iam/add-application
     * Registers an application in your organization — one product or site your people sign in to, with its own client credentials, sign-in methods and allowed redirect URIs.
     * Registers an application in your organization — one product or site your people sign in to, with its own client credentials, sign-in methods and allowed redirect URIs.  The older spelling of POST /v1/iam/application. A name already used in the organization is refused rather than overwritten.
     * @param iamApplication 
     * @return IamResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun postIamAddApplication(iamApplication: IamApplication) : IamResponse {
        val localVarResponse = postIamAddApplicationWithHttpInfo(iamApplication = iamApplication)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as IamResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/iam/add-application
     * Registers an application in your organization — one product or site your people sign in to, with its own client credentials, sign-in methods and allowed redirect URIs.
     * Registers an application in your organization — one product or site your people sign in to, with its own client credentials, sign-in methods and allowed redirect URIs.  The older spelling of POST /v1/iam/application. A name already used in the organization is refused rather than overwritten.
     * @param iamApplication 
     * @return ApiResponse<IamResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun postIamAddApplicationWithHttpInfo(iamApplication: IamApplication) : ApiResponse<IamResponse?> {
        val localVariableConfig = postIamAddApplicationRequestConfig(iamApplication = iamApplication)

        return request<IamApplication, IamResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation postIamAddApplication
     *
     * @param iamApplication 
     * @return RequestConfig
     */
    fun postIamAddApplicationRequestConfig(iamApplication: IamApplication) : RequestConfig<IamApplication> {
        val localVariableBody = iamApplication
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/iam/add-application",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * POST /v1/iam/add-organization
     * Creates an organization — the account everything else in your directory hangs from.
     * Creates an organization — the account everything else in your directory hangs from. Users, applications, roles, projects and workspaces are all named inside one organization, so this is the first write in a new tenant.  The older spelling of POST /v1/iam/organizations. Both reach the same create, so a name already taken is refused here too.
     * @param iamCreateOrganizationInput 
     * @return IamResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun postIamAddOrganization(iamCreateOrganizationInput: IamCreateOrganizationInput) : IamResponse {
        val localVarResponse = postIamAddOrganizationWithHttpInfo(iamCreateOrganizationInput = iamCreateOrganizationInput)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as IamResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/iam/add-organization
     * Creates an organization — the account everything else in your directory hangs from.
     * Creates an organization — the account everything else in your directory hangs from. Users, applications, roles, projects and workspaces are all named inside one organization, so this is the first write in a new tenant.  The older spelling of POST /v1/iam/organizations. Both reach the same create, so a name already taken is refused here too.
     * @param iamCreateOrganizationInput 
     * @return ApiResponse<IamResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun postIamAddOrganizationWithHttpInfo(iamCreateOrganizationInput: IamCreateOrganizationInput) : ApiResponse<IamResponse?> {
        val localVariableConfig = postIamAddOrganizationRequestConfig(iamCreateOrganizationInput = iamCreateOrganizationInput)

        return request<IamCreateOrganizationInput, IamResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation postIamAddOrganization
     *
     * @param iamCreateOrganizationInput 
     * @return RequestConfig
     */
    fun postIamAddOrganizationRequestConfig(iamCreateOrganizationInput: IamCreateOrganizationInput) : RequestConfig<IamCreateOrganizationInput> {
        val localVariableBody = iamCreateOrganizationInput
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/iam/add-organization",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * POST /v1/iam/add-project
     * Creates a project inside your organization — the scope people pick between when their work is separated by product or client rather than by team.
     * Creates a project inside your organization — the scope people pick between when their work is separated by product or client rather than by team.  The older spelling of POST /v1/iam/projects. Creating one takes an administrator of the owning organization.
     * @param iamInput 
     * @return IamResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun postIamAddProject(iamInput: IamInput) : IamResponse {
        val localVarResponse = postIamAddProjectWithHttpInfo(iamInput = iamInput)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as IamResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/iam/add-project
     * Creates a project inside your organization — the scope people pick between when their work is separated by product or client rather than by team.
     * Creates a project inside your organization — the scope people pick between when their work is separated by product or client rather than by team.  The older spelling of POST /v1/iam/projects. Creating one takes an administrator of the owning organization.
     * @param iamInput 
     * @return ApiResponse<IamResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun postIamAddProjectWithHttpInfo(iamInput: IamInput) : ApiResponse<IamResponse?> {
        val localVariableConfig = postIamAddProjectRequestConfig(iamInput = iamInput)

        return request<IamInput, IamResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation postIamAddProject
     *
     * @param iamInput 
     * @return RequestConfig
     */
    fun postIamAddProjectRequestConfig(iamInput: IamInput) : RequestConfig<IamInput> {
        val localVariableBody = iamInput
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/iam/add-project",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * POST /v1/iam/add-provider
     * Adds an identity provider your people can sign in with, or a service your applications send through — a social or enterprise login, an email or SMS sender, a storage or payment connector.
     * Adds an identity provider your people can sign in with, or a service your applications send through — a social or enterprise login, an email or SMS sender, a storage or payment connector.  A provider is configured once here and then switched on per application, so several applications can share one set of credentials.  The older spelling of POST /v1/iam/providers.
     * @param iamProvider 
     * @return IamResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun postIamAddProvider(iamProvider: IamProvider) : IamResponse {
        val localVarResponse = postIamAddProviderWithHttpInfo(iamProvider = iamProvider)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as IamResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/iam/add-provider
     * Adds an identity provider your people can sign in with, or a service your applications send through — a social or enterprise login, an email or SMS sender, a storage or payment connector.
     * Adds an identity provider your people can sign in with, or a service your applications send through — a social or enterprise login, an email or SMS sender, a storage or payment connector.  A provider is configured once here and then switched on per application, so several applications can share one set of credentials.  The older spelling of POST /v1/iam/providers.
     * @param iamProvider 
     * @return ApiResponse<IamResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun postIamAddProviderWithHttpInfo(iamProvider: IamProvider) : ApiResponse<IamResponse?> {
        val localVariableConfig = postIamAddProviderRequestConfig(iamProvider = iamProvider)

        return request<IamProvider, IamResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation postIamAddProvider
     *
     * @param iamProvider 
     * @return RequestConfig
     */
    fun postIamAddProviderRequestConfig(iamProvider: IamProvider) : RequestConfig<IamProvider> {
        val localVariableBody = iamProvider
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/iam/add-provider",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * POST /v1/iam/add-role
     * Creates a role — a named group of people that permissions are granted to.
     * Creates a role — a named group of people that permissions are granted to. Granting to a role rather than to each person is what keeps access correct as your team changes: add someone to the role and they inherit everything it can do.  The older spelling of POST /v1/iam/roles.
     * @param iamrolesInput 
     * @return IamResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun postIamAddRole(iamrolesInput: IamrolesInput) : IamResponse {
        val localVarResponse = postIamAddRoleWithHttpInfo(iamrolesInput = iamrolesInput)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as IamResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/iam/add-role
     * Creates a role — a named group of people that permissions are granted to.
     * Creates a role — a named group of people that permissions are granted to. Granting to a role rather than to each person is what keeps access correct as your team changes: add someone to the role and they inherit everything it can do.  The older spelling of POST /v1/iam/roles.
     * @param iamrolesInput 
     * @return ApiResponse<IamResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun postIamAddRoleWithHttpInfo(iamrolesInput: IamrolesInput) : ApiResponse<IamResponse?> {
        val localVariableConfig = postIamAddRoleRequestConfig(iamrolesInput = iamrolesInput)

        return request<IamrolesInput, IamResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation postIamAddRole
     *
     * @param iamrolesInput 
     * @return RequestConfig
     */
    fun postIamAddRoleRequestConfig(iamrolesInput: IamrolesInput) : RequestConfig<IamrolesInput> {
        val localVariableBody = iamrolesInput
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/iam/add-role",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * POST /v1/iam/add-user
     * Adds a person to your organization and, if you send a password, sets the one they will sign in with.
     * Adds a person to your organization and, if you send a password, sets the one they will sign in with. The password is hashed before it is stored and is never returned to you or to anyone else.  Usernames are checked against one rule wherever an account is created — this verb, password signup, a social sign-in, or SCIM — so a name accepted here is a name accepted everywhere.  The older spelling of POST /v1/iam/users, and it posts the user&#39;s fields at the top level rather than wrapped in {user, password}.
     * @param iamuserBody 
     * @return IamResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun postIamAddUser(iamuserBody: IamuserBody) : IamResponse {
        val localVarResponse = postIamAddUserWithHttpInfo(iamuserBody = iamuserBody)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as IamResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/iam/add-user
     * Adds a person to your organization and, if you send a password, sets the one they will sign in with.
     * Adds a person to your organization and, if you send a password, sets the one they will sign in with. The password is hashed before it is stored and is never returned to you or to anyone else.  Usernames are checked against one rule wherever an account is created — this verb, password signup, a social sign-in, or SCIM — so a name accepted here is a name accepted everywhere.  The older spelling of POST /v1/iam/users, and it posts the user&#39;s fields at the top level rather than wrapped in {user, password}.
     * @param iamuserBody 
     * @return ApiResponse<IamResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun postIamAddUserWithHttpInfo(iamuserBody: IamuserBody) : ApiResponse<IamResponse?> {
        val localVariableConfig = postIamAddUserRequestConfig(iamuserBody = iamuserBody)

        return request<IamuserBody, IamResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation postIamAddUser
     *
     * @param iamuserBody 
     * @return RequestConfig
     */
    fun postIamAddUserRequestConfig(iamuserBody: IamuserBody) : RequestConfig<IamuserBody> {
        val localVariableBody = iamuserBody
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/iam/add-user",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * POST /v1/iam/add-workspace
     * Creates a workspace inside your organization — the scope a team works in, alongside projects rather than instead of them.
     * Creates a workspace inside your organization — the scope a team works in, alongside projects rather than instead of them.  The older spelling of POST /v1/iam/workspaces. Creating one takes an administrator of the owning organization.
     * @param iamworkspacesInput 
     * @return IamResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun postIamAddWorkspace(iamworkspacesInput: IamworkspacesInput) : IamResponse {
        val localVarResponse = postIamAddWorkspaceWithHttpInfo(iamworkspacesInput = iamworkspacesInput)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as IamResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/iam/add-workspace
     * Creates a workspace inside your organization — the scope a team works in, alongside projects rather than instead of them.
     * Creates a workspace inside your organization — the scope a team works in, alongside projects rather than instead of them.  The older spelling of POST /v1/iam/workspaces. Creating one takes an administrator of the owning organization.
     * @param iamworkspacesInput 
     * @return ApiResponse<IamResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun postIamAddWorkspaceWithHttpInfo(iamworkspacesInput: IamworkspacesInput) : ApiResponse<IamResponse?> {
        val localVariableConfig = postIamAddWorkspaceRequestConfig(iamworkspacesInput = iamworkspacesInput)

        return request<IamworkspacesInput, IamResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation postIamAddWorkspace
     *
     * @param iamworkspacesInput 
     * @return RequestConfig
     */
    fun postIamAddWorkspaceRequestConfig(iamworkspacesInput: IamworkspacesInput) : RequestConfig<IamworkspacesInput> {
        val localVariableBody = iamworkspacesInput
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/iam/add-workspace",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * POST /v1/iam/application
     * Registers an application in your organization — one product or site your people sign in to, with its own client credentials, sign-in methods and allowed redirect URIs.
     * Registers an application in your organization — one product or site your people sign in to, with its own client credentials, sign-in methods and allowed redirect URIs. A name already used in the organization is refused rather than overwritten.  Exported so the legacy add-application alias reuses this exact path — one create, two spellings.
     * @param iamApplication 
     * @return IamApplication
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun postIamApplication(iamApplication: IamApplication) : IamApplication {
        val localVarResponse = postIamApplicationWithHttpInfo(iamApplication = iamApplication)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as IamApplication
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/iam/application
     * Registers an application in your organization — one product or site your people sign in to, with its own client credentials, sign-in methods and allowed redirect URIs.
     * Registers an application in your organization — one product or site your people sign in to, with its own client credentials, sign-in methods and allowed redirect URIs. A name already used in the organization is refused rather than overwritten.  Exported so the legacy add-application alias reuses this exact path — one create, two spellings.
     * @param iamApplication 
     * @return ApiResponse<IamApplication?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun postIamApplicationWithHttpInfo(iamApplication: IamApplication) : ApiResponse<IamApplication?> {
        val localVariableConfig = postIamApplicationRequestConfig(iamApplication = iamApplication)

        return request<IamApplication, IamApplication>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation postIamApplication
     *
     * @param iamApplication 
     * @return RequestConfig
     */
    fun postIamApplicationRequestConfig(iamApplication: IamApplication) : RequestConfig<IamApplication> {
        val localVariableBody = iamApplication
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/iam/application",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * POST /v1/iam/delete-application
     * Deletes an application.
     * Deletes an application. Anyone mid-sign-in through it is turned away and its client credentials stop working, so retire the integration first.  The older spelling of DELETE /v1/iam/application.
     * @param iamApplication 
     * @return IamResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun postIamDeleteApplication(iamApplication: IamApplication) : IamResponse {
        val localVarResponse = postIamDeleteApplicationWithHttpInfo(iamApplication = iamApplication)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as IamResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/iam/delete-application
     * Deletes an application.
     * Deletes an application. Anyone mid-sign-in through it is turned away and its client credentials stop working, so retire the integration first.  The older spelling of DELETE /v1/iam/application.
     * @param iamApplication 
     * @return ApiResponse<IamResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun postIamDeleteApplicationWithHttpInfo(iamApplication: IamApplication) : ApiResponse<IamResponse?> {
        val localVariableConfig = postIamDeleteApplicationRequestConfig(iamApplication = iamApplication)

        return request<IamApplication, IamResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation postIamDeleteApplication
     *
     * @param iamApplication 
     * @return RequestConfig
     */
    fun postIamDeleteApplicationRequestConfig(iamApplication: IamApplication) : RequestConfig<IamApplication> {
        val localVariableBody = iamApplication
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/iam/delete-application",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * POST /v1/iam/delete-organization
     * Deletes an organization and everything named inside it — its users, applications, roles, projects and workspaces.
     * Deletes an organization and everything named inside it — its users, applications, roles, projects and workspaces. There is no undo, and every session issued under it stops working.  The older spelling of POST /v1/iam/organizations/delete.
     * @param iamDeleteOrganizationInput 
     * @return IamResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun postIamDeleteOrganization(iamDeleteOrganizationInput: IamDeleteOrganizationInput) : IamResponse {
        val localVarResponse = postIamDeleteOrganizationWithHttpInfo(iamDeleteOrganizationInput = iamDeleteOrganizationInput)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as IamResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/iam/delete-organization
     * Deletes an organization and everything named inside it — its users, applications, roles, projects and workspaces.
     * Deletes an organization and everything named inside it — its users, applications, roles, projects and workspaces. There is no undo, and every session issued under it stops working.  The older spelling of POST /v1/iam/organizations/delete.
     * @param iamDeleteOrganizationInput 
     * @return ApiResponse<IamResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun postIamDeleteOrganizationWithHttpInfo(iamDeleteOrganizationInput: IamDeleteOrganizationInput) : ApiResponse<IamResponse?> {
        val localVariableConfig = postIamDeleteOrganizationRequestConfig(iamDeleteOrganizationInput = iamDeleteOrganizationInput)

        return request<IamDeleteOrganizationInput, IamResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation postIamDeleteOrganization
     *
     * @param iamDeleteOrganizationInput 
     * @return RequestConfig
     */
    fun postIamDeleteOrganizationRequestConfig(iamDeleteOrganizationInput: IamDeleteOrganizationInput) : RequestConfig<IamDeleteOrganizationInput> {
        val localVariableBody = iamDeleteOrganizationInput
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/iam/delete-organization",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * POST /v1/iam/delete-project
     * Deletes a project.
     * Deletes a project. The people and roles in your organization are unchanged; what goes is the scope itself, so anything addressed by it must move first.  The older spelling of POST /v1/iam/projects/delete.
     * @param iamprojectsRef 
     * @return IamResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun postIamDeleteProject(iamprojectsRef: IamprojectsRef) : IamResponse {
        val localVarResponse = postIamDeleteProjectWithHttpInfo(iamprojectsRef = iamprojectsRef)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as IamResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/iam/delete-project
     * Deletes a project.
     * Deletes a project. The people and roles in your organization are unchanged; what goes is the scope itself, so anything addressed by it must move first.  The older spelling of POST /v1/iam/projects/delete.
     * @param iamprojectsRef 
     * @return ApiResponse<IamResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun postIamDeleteProjectWithHttpInfo(iamprojectsRef: IamprojectsRef) : ApiResponse<IamResponse?> {
        val localVariableConfig = postIamDeleteProjectRequestConfig(iamprojectsRef = iamprojectsRef)

        return request<IamprojectsRef, IamResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation postIamDeleteProject
     *
     * @param iamprojectsRef 
     * @return RequestConfig
     */
    fun postIamDeleteProjectRequestConfig(iamprojectsRef: IamprojectsRef) : RequestConfig<IamprojectsRef> {
        val localVariableBody = iamprojectsRef
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/iam/delete-project",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * POST /v1/iam/delete-provider
     * Removes a provider.
     * Removes a provider. Sign-in through it stops for every application that used it, so detach those applications first if they have no other method.  The older spelling of POST /v1/iam/providers/delete.
     * @param iamProvider 
     * @return IamResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun postIamDeleteProvider(iamProvider: IamProvider) : IamResponse {
        val localVarResponse = postIamDeleteProviderWithHttpInfo(iamProvider = iamProvider)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as IamResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/iam/delete-provider
     * Removes a provider.
     * Removes a provider. Sign-in through it stops for every application that used it, so detach those applications first if they have no other method.  The older spelling of POST /v1/iam/providers/delete.
     * @param iamProvider 
     * @return ApiResponse<IamResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun postIamDeleteProviderWithHttpInfo(iamProvider: IamProvider) : ApiResponse<IamResponse?> {
        val localVariableConfig = postIamDeleteProviderRequestConfig(iamProvider = iamProvider)

        return request<IamProvider, IamResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation postIamDeleteProvider
     *
     * @param iamProvider 
     * @return RequestConfig
     */
    fun postIamDeleteProviderRequestConfig(iamProvider: IamProvider) : RequestConfig<IamProvider> {
        val localVariableBody = iamProvider
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/iam/delete-provider",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * POST /v1/iam/delete-role
     * Deletes a role.
     * Deletes a role. Everyone in it loses the access it carried; their accounts and any other roles they hold are untouched.  The older spelling of POST /v1/iam/roles/delete.
     * @param iamrolesRef 
     * @return IamResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun postIamDeleteRole(iamrolesRef: IamrolesRef) : IamResponse {
        val localVarResponse = postIamDeleteRoleWithHttpInfo(iamrolesRef = iamrolesRef)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as IamResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/iam/delete-role
     * Deletes a role.
     * Deletes a role. Everyone in it loses the access it carried; their accounts and any other roles they hold are untouched.  The older spelling of POST /v1/iam/roles/delete.
     * @param iamrolesRef 
     * @return ApiResponse<IamResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun postIamDeleteRoleWithHttpInfo(iamrolesRef: IamrolesRef) : ApiResponse<IamResponse?> {
        val localVariableConfig = postIamDeleteRoleRequestConfig(iamrolesRef = iamrolesRef)

        return request<IamrolesRef, IamResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation postIamDeleteRole
     *
     * @param iamrolesRef 
     * @return RequestConfig
     */
    fun postIamDeleteRoleRequestConfig(iamrolesRef: IamrolesRef) : RequestConfig<IamrolesRef> {
        val localVariableBody = iamrolesRef
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/iam/delete-role",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * POST /v1/iam/delete-user
     * Removes a person from your organization.
     * Removes a person from your organization. Their sessions stop working and the account is gone, not suspended — to keep the record and only stop sign-in, update the user instead.  The older spelling of POST /v1/iam/users/delete.
     * @param iamuserBody 
     * @return IamResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun postIamDeleteUser(iamuserBody: IamuserBody) : IamResponse {
        val localVarResponse = postIamDeleteUserWithHttpInfo(iamuserBody = iamuserBody)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as IamResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/iam/delete-user
     * Removes a person from your organization.
     * Removes a person from your organization. Their sessions stop working and the account is gone, not suspended — to keep the record and only stop sign-in, update the user instead.  The older spelling of POST /v1/iam/users/delete.
     * @param iamuserBody 
     * @return ApiResponse<IamResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun postIamDeleteUserWithHttpInfo(iamuserBody: IamuserBody) : ApiResponse<IamResponse?> {
        val localVariableConfig = postIamDeleteUserRequestConfig(iamuserBody = iamuserBody)

        return request<IamuserBody, IamResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation postIamDeleteUser
     *
     * @param iamuserBody 
     * @return RequestConfig
     */
    fun postIamDeleteUserRequestConfig(iamuserBody: IamuserBody) : RequestConfig<IamuserBody> {
        val localVariableBody = iamuserBody
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/iam/delete-user",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * POST /v1/iam/delete-workspace
     * Deletes a workspace.
     * Deletes a workspace. The people and roles in your organization are unchanged; what goes is the scope itself.  The older spelling of POST /v1/iam/workspaces/delete.
     * @param iamworkspacesRef 
     * @return IamResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun postIamDeleteWorkspace(iamworkspacesRef: IamworkspacesRef) : IamResponse {
        val localVarResponse = postIamDeleteWorkspaceWithHttpInfo(iamworkspacesRef = iamworkspacesRef)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as IamResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/iam/delete-workspace
     * Deletes a workspace.
     * Deletes a workspace. The people and roles in your organization are unchanged; what goes is the scope itself.  The older spelling of POST /v1/iam/workspaces/delete.
     * @param iamworkspacesRef 
     * @return ApiResponse<IamResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun postIamDeleteWorkspaceWithHttpInfo(iamworkspacesRef: IamworkspacesRef) : ApiResponse<IamResponse?> {
        val localVariableConfig = postIamDeleteWorkspaceRequestConfig(iamworkspacesRef = iamworkspacesRef)

        return request<IamworkspacesRef, IamResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation postIamDeleteWorkspace
     *
     * @param iamworkspacesRef 
     * @return RequestConfig
     */
    fun postIamDeleteWorkspaceRequestConfig(iamworkspacesRef: IamworkspacesRef) : RequestConfig<IamworkspacesRef> {
        val localVariableBody = iamworkspacesRef
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/iam/delete-workspace",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * POST /v1/iam/update-application
     * Updates one of your applications — its display, its sign-in methods and the redirect URIs it is allowed to return to.
     * Updates one of your applications — its display, its sign-in methods and the redirect URIs it is allowed to return to. Which organization and name the application has are fixed when it is created and are not editable here.  A redirect URI you add becomes an allowed sign-in origin, so this is the call that makes login work from a new host.  The older spelling of PUT /v1/iam/application.
     * @param iamApplication 
     * @return IamResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun postIamUpdateApplication(iamApplication: IamApplication) : IamResponse {
        val localVarResponse = postIamUpdateApplicationWithHttpInfo(iamApplication = iamApplication)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as IamResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/iam/update-application
     * Updates one of your applications — its display, its sign-in methods and the redirect URIs it is allowed to return to.
     * Updates one of your applications — its display, its sign-in methods and the redirect URIs it is allowed to return to. Which organization and name the application has are fixed when it is created and are not editable here.  A redirect URI you add becomes an allowed sign-in origin, so this is the call that makes login work from a new host.  The older spelling of PUT /v1/iam/application.
     * @param iamApplication 
     * @return ApiResponse<IamResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun postIamUpdateApplicationWithHttpInfo(iamApplication: IamApplication) : ApiResponse<IamResponse?> {
        val localVariableConfig = postIamUpdateApplicationRequestConfig(iamApplication = iamApplication)

        return request<IamApplication, IamResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation postIamUpdateApplication
     *
     * @param iamApplication 
     * @return RequestConfig
     */
    fun postIamUpdateApplicationRequestConfig(iamApplication: IamApplication) : RequestConfig<IamApplication> {
        val localVariableBody = iamApplication
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/iam/update-application",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * POST /v1/iam/update-organization
     * Updates your organization — its display, its default settings and the sign-in rules everyone in it inherits.
     * Updates your organization — its display, its default settings and the sign-in rules everyone in it inherits.  The older spelling of POST /v1/iam/organizations/update.
     * @param iamUpdateOrganizationInput 
     * @return IamResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun postIamUpdateOrganization(iamUpdateOrganizationInput: IamUpdateOrganizationInput) : IamResponse {
        val localVarResponse = postIamUpdateOrganizationWithHttpInfo(iamUpdateOrganizationInput = iamUpdateOrganizationInput)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as IamResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/iam/update-organization
     * Updates your organization — its display, its default settings and the sign-in rules everyone in it inherits.
     * Updates your organization — its display, its default settings and the sign-in rules everyone in it inherits.  The older spelling of POST /v1/iam/organizations/update.
     * @param iamUpdateOrganizationInput 
     * @return ApiResponse<IamResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun postIamUpdateOrganizationWithHttpInfo(iamUpdateOrganizationInput: IamUpdateOrganizationInput) : ApiResponse<IamResponse?> {
        val localVariableConfig = postIamUpdateOrganizationRequestConfig(iamUpdateOrganizationInput = iamUpdateOrganizationInput)

        return request<IamUpdateOrganizationInput, IamResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation postIamUpdateOrganization
     *
     * @param iamUpdateOrganizationInput 
     * @return RequestConfig
     */
    fun postIamUpdateOrganizationRequestConfig(iamUpdateOrganizationInput: IamUpdateOrganizationInput) : RequestConfig<IamUpdateOrganizationInput> {
        val localVariableBody = iamUpdateOrganizationInput
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/iam/update-organization",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * POST /v1/iam/update-provider
     * Updates a provider&#39;s settings or rotates the credentials it holds.
     * Updates a provider&#39;s settings or rotates the credentials it holds. The change takes effect on the next sign-in through it — sessions already issued are unaffected.  The older spelling of POST /v1/iam/providers/update.
     * @param iamProvider 
     * @return IamResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun postIamUpdateProvider(iamProvider: IamProvider) : IamResponse {
        val localVarResponse = postIamUpdateProviderWithHttpInfo(iamProvider = iamProvider)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as IamResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/iam/update-provider
     * Updates a provider&#39;s settings or rotates the credentials it holds.
     * Updates a provider&#39;s settings or rotates the credentials it holds. The change takes effect on the next sign-in through it — sessions already issued are unaffected.  The older spelling of POST /v1/iam/providers/update.
     * @param iamProvider 
     * @return ApiResponse<IamResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun postIamUpdateProviderWithHttpInfo(iamProvider: IamProvider) : ApiResponse<IamResponse?> {
        val localVariableConfig = postIamUpdateProviderRequestConfig(iamProvider = iamProvider)

        return request<IamProvider, IamResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation postIamUpdateProvider
     *
     * @param iamProvider 
     * @return RequestConfig
     */
    fun postIamUpdateProviderRequestConfig(iamProvider: IamProvider) : RequestConfig<IamProvider> {
        val localVariableBody = iamProvider
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/iam/update-provider",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * POST /v1/iam/update-role
     * Updates a role&#39;s members or the roles it includes.
     * Updates a role&#39;s members or the roles it includes. Access changes for everyone in it as soon as the write lands.  The older spelling of POST /v1/iam/roles/update.
     * @param iamrolesInput 
     * @return IamResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun postIamUpdateRole(iamrolesInput: IamrolesInput) : IamResponse {
        val localVarResponse = postIamUpdateRoleWithHttpInfo(iamrolesInput = iamrolesInput)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as IamResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/iam/update-role
     * Updates a role&#39;s members or the roles it includes.
     * Updates a role&#39;s members or the roles it includes. Access changes for everyone in it as soon as the write lands.  The older spelling of POST /v1/iam/roles/update.
     * @param iamrolesInput 
     * @return ApiResponse<IamResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun postIamUpdateRoleWithHttpInfo(iamrolesInput: IamrolesInput) : ApiResponse<IamResponse?> {
        val localVariableConfig = postIamUpdateRoleRequestConfig(iamrolesInput = iamrolesInput)

        return request<IamrolesInput, IamResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation postIamUpdateRole
     *
     * @param iamrolesInput 
     * @return RequestConfig
     */
    fun postIamUpdateRoleRequestConfig(iamrolesInput: IamrolesInput) : RequestConfig<IamrolesInput> {
        val localVariableBody = iamrolesInput
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/iam/update-role",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * POST /v1/iam/update-user
     * Updates one of your users&#39; profile, roles or credentials.
     * Updates one of your users&#39; profile, roles or credentials. Send a password to reset it; leave it out and the current one stands.  The older spelling of POST /v1/iam/users/update, with the user&#39;s fields at the top level rather than wrapped in {user, password}.
     * @param iamuserBody 
     * @return IamResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun postIamUpdateUser(iamuserBody: IamuserBody) : IamResponse {
        val localVarResponse = postIamUpdateUserWithHttpInfo(iamuserBody = iamuserBody)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as IamResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/iam/update-user
     * Updates one of your users&#39; profile, roles or credentials.
     * Updates one of your users&#39; profile, roles or credentials. Send a password to reset it; leave it out and the current one stands.  The older spelling of POST /v1/iam/users/update, with the user&#39;s fields at the top level rather than wrapped in {user, password}.
     * @param iamuserBody 
     * @return ApiResponse<IamResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun postIamUpdateUserWithHttpInfo(iamuserBody: IamuserBody) : ApiResponse<IamResponse?> {
        val localVariableConfig = postIamUpdateUserRequestConfig(iamuserBody = iamuserBody)

        return request<IamuserBody, IamResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation postIamUpdateUser
     *
     * @param iamuserBody 
     * @return RequestConfig
     */
    fun postIamUpdateUserRequestConfig(iamuserBody: IamuserBody) : RequestConfig<IamuserBody> {
        val localVariableBody = iamuserBody
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/iam/update-user",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * PUT /v1/iam/application
     * Changes an application&#39;s display, its sign-in methods and the redirect URIs it may return to — the call that makes login work from a new host.
     * Changes an application&#39;s display, its sign-in methods and the redirect URIs it may return to — the call that makes login work from a new host. Which organization it belongs to and what it is named are fixed when it is created and are not editable here.  Exported so the legacy update-application alias reuses this exact path — one update, two spellings.
     * @param iamApplication 
     * @return IamApplication
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun putIamApplication(iamApplication: IamApplication) : IamApplication {
        val localVarResponse = putIamApplicationWithHttpInfo(iamApplication = iamApplication)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as IamApplication
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /v1/iam/application
     * Changes an application&#39;s display, its sign-in methods and the redirect URIs it may return to — the call that makes login work from a new host.
     * Changes an application&#39;s display, its sign-in methods and the redirect URIs it may return to — the call that makes login work from a new host. Which organization it belongs to and what it is named are fixed when it is created and are not editable here.  Exported so the legacy update-application alias reuses this exact path — one update, two spellings.
     * @param iamApplication 
     * @return ApiResponse<IamApplication?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun putIamApplicationWithHttpInfo(iamApplication: IamApplication) : ApiResponse<IamApplication?> {
        val localVariableConfig = putIamApplicationRequestConfig(iamApplication = iamApplication)

        return request<IamApplication, IamApplication>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation putIamApplication
     *
     * @param iamApplication 
     * @return RequestConfig
     */
    fun putIamApplicationRequestConfig(iamApplication: IamApplication) : RequestConfig<IamApplication> {
        val localVariableBody = iamApplication
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/v1/iam/application",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
