/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.api

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import ai.hanzo.cloud.model.CloudErrorList

import com.google.gson.annotations.SerializedName

import ai.hanzo.cloud.infrastructure.ApiClient
import ai.hanzo.cloud.infrastructure.ApiResponse
import ai.hanzo.cloud.infrastructure.ClientException
import ai.hanzo.cloud.infrastructure.ClientError
import ai.hanzo.cloud.infrastructure.ServerException
import ai.hanzo.cloud.infrastructure.ServerError
import ai.hanzo.cloud.infrastructure.MultiValueMap
import ai.hanzo.cloud.infrastructure.PartConfig
import ai.hanzo.cloud.infrastructure.RequestConfig
import ai.hanzo.cloud.infrastructure.RequestMethod
import ai.hanzo.cloud.infrastructure.ResponseType
import ai.hanzo.cloud.infrastructure.Success
import ai.hanzo.cloud.infrastructure.toMultiValue

class ErrorsApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "https://api.hanzo.ai")
        }
    }

    /**
     * GET /v1/errors
     * Errors returns the caller org&#39;s most recently captured errors, newest first.
     * Errors returns the caller org&#39;s most recently captured errors, newest first. The error-tracking read view over the same table the capture doors write: only rows stored as type &#39;error&#39;, each with its captured exception lifted out of the property bag as a first-class field.  The org is the validated principal&#39;s — never a parameter — and this read requires a real bearer, NEVER the write-only publishable key: pk- can attribute a write and can read nothing. 403 without a validated bearer, 503 when the warehouse is unreachable.
     * @param limit Limit is how many rows to return, newest first. Default 50, maximum 200; a value at or below zero, or one that is not a number, takes the default. (optional)
     * @return CloudErrorList
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun cloudGetV1Errors(limit: kotlin.Int? = null) : CloudErrorList {
        val localVarResponse = cloudGetV1ErrorsWithHttpInfo(limit = limit)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CloudErrorList
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/errors
     * Errors returns the caller org&#39;s most recently captured errors, newest first.
     * Errors returns the caller org&#39;s most recently captured errors, newest first. The error-tracking read view over the same table the capture doors write: only rows stored as type &#39;error&#39;, each with its captured exception lifted out of the property bag as a first-class field.  The org is the validated principal&#39;s — never a parameter — and this read requires a real bearer, NEVER the write-only publishable key: pk- can attribute a write and can read nothing. 403 without a validated bearer, 503 when the warehouse is unreachable.
     * @param limit Limit is how many rows to return, newest first. Default 50, maximum 200; a value at or below zero, or one that is not a number, takes the default. (optional)
     * @return ApiResponse<CloudErrorList?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun cloudGetV1ErrorsWithHttpInfo(limit: kotlin.Int?) : ApiResponse<CloudErrorList?> {
        val localVariableConfig = cloudGetV1ErrorsRequestConfig(limit = limit)

        return request<Unit, CloudErrorList>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation cloudGetV1Errors
     *
     * @param limit Limit is how many rows to return, newest first. Default 50, maximum 200; a value at or below zero, or one that is not a number, takes the default. (optional)
     * @return RequestConfig
     */
    fun cloudGetV1ErrorsRequestConfig(limit: kotlin.Int?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/errors",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
