/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.api

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import ai.hanzo.cloud.model.CloudCaptureResult
import ai.hanzo.cloud.model.CloudPostV1EventRequest

import com.google.gson.annotations.SerializedName

import ai.hanzo.cloud.infrastructure.ApiClient
import ai.hanzo.cloud.infrastructure.ApiResponse
import ai.hanzo.cloud.infrastructure.ClientException
import ai.hanzo.cloud.infrastructure.ClientError
import ai.hanzo.cloud.infrastructure.ServerException
import ai.hanzo.cloud.infrastructure.ServerError
import ai.hanzo.cloud.infrastructure.MultiValueMap
import ai.hanzo.cloud.infrastructure.PartConfig
import ai.hanzo.cloud.infrastructure.RequestConfig
import ai.hanzo.cloud.infrastructure.RequestMethod
import ai.hanzo.cloud.infrastructure.ResponseType
import ai.hanzo.cloud.infrastructure.Success
import ai.hanzo.cloud.infrastructure.toMultiValue

class EventApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "https://api.hanzo.ai")
        }
    }

    /**
     * POST /v1/event
     * 
     * 
     * @param cloudPostV1EventRequest  (optional)
     * @return CloudCaptureResult
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun cloudPostV1Event(cloudPostV1EventRequest: CloudPostV1EventRequest? = null) : CloudCaptureResult {
        val localVarResponse = cloudPostV1EventWithHttpInfo(cloudPostV1EventRequest = cloudPostV1EventRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CloudCaptureResult
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/event
     * 
     * 
     * @param cloudPostV1EventRequest  (optional)
     * @return ApiResponse<CloudCaptureResult?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun cloudPostV1EventWithHttpInfo(cloudPostV1EventRequest: CloudPostV1EventRequest?) : ApiResponse<CloudCaptureResult?> {
        val localVariableConfig = cloudPostV1EventRequestConfig(cloudPostV1EventRequest = cloudPostV1EventRequest)

        return request<CloudPostV1EventRequest, CloudCaptureResult>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation cloudPostV1Event
     *
     * @param cloudPostV1EventRequest  (optional)
     * @return RequestConfig
     */
    fun cloudPostV1EventRequestConfig(cloudPostV1EventRequest: CloudPostV1EventRequest?) : RequestConfig<CloudPostV1EventRequest> {
        val localVariableBody = cloudPostV1EventRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/event",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /v1/event/{project}/envelope
     * 
     * 
     * @param project 
     * @param body  (optional)
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun cloudPostV1EventByProjectEnvelope(project: kotlin.String, body: java.io.File? = null) : Unit {
        val localVarResponse = cloudPostV1EventByProjectEnvelopeWithHttpInfo(project = project, body = body)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/event/{project}/envelope
     * 
     * 
     * @param project 
     * @param body  (optional)
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun cloudPostV1EventByProjectEnvelopeWithHttpInfo(project: kotlin.String, body: java.io.File?) : ApiResponse<Unit?> {
        val localVariableConfig = cloudPostV1EventByProjectEnvelopeRequestConfig(project = project, body = body)

        return request<java.io.File, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation cloudPostV1EventByProjectEnvelope
     *
     * @param project 
     * @param body  (optional)
     * @return RequestConfig
     */
    fun cloudPostV1EventByProjectEnvelopeRequestConfig(project: kotlin.String, body: java.io.File?) : RequestConfig<java.io.File> {
        val localVariableBody = body
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/octet-stream"
        
        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/event/{project}/envelope".replace("{"+"project"+"}", encodeURIComponent(project.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /v1/event/{project}/store
     * 
     * 
     * @param project 
     * @param body  (optional)
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun cloudPostV1EventByProjectStore(project: kotlin.String, body: java.io.File? = null) : Unit {
        val localVarResponse = cloudPostV1EventByProjectStoreWithHttpInfo(project = project, body = body)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/event/{project}/store
     * 
     * 
     * @param project 
     * @param body  (optional)
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun cloudPostV1EventByProjectStoreWithHttpInfo(project: kotlin.String, body: java.io.File?) : ApiResponse<Unit?> {
        val localVariableConfig = cloudPostV1EventByProjectStoreRequestConfig(project = project, body = body)

        return request<java.io.File, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation cloudPostV1EventByProjectStore
     *
     * @param project 
     * @param body  (optional)
     * @return RequestConfig
     */
    fun cloudPostV1EventByProjectStoreRequestConfig(project: kotlin.String, body: java.io.File?) : RequestConfig<java.io.File> {
        val localVariableBody = body
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/octet-stream"
        
        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/event/{project}/store".replace("{"+"project"+"}", encodeURIComponent(project.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
