/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.api

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import ai.hanzo.cloud.model.MeshServiceList

import com.google.gson.annotations.SerializedName

import ai.hanzo.cloud.infrastructure.ApiClient
import ai.hanzo.cloud.infrastructure.ApiResponse
import ai.hanzo.cloud.infrastructure.ClientException
import ai.hanzo.cloud.infrastructure.ClientError
import ai.hanzo.cloud.infrastructure.ServerException
import ai.hanzo.cloud.infrastructure.ServerError
import ai.hanzo.cloud.infrastructure.MultiValueMap
import ai.hanzo.cloud.infrastructure.PartConfig
import ai.hanzo.cloud.infrastructure.RequestConfig
import ai.hanzo.cloud.infrastructure.RequestMethod
import ai.hanzo.cloud.infrastructure.ResponseType
import ai.hanzo.cloud.infrastructure.Success
import ai.hanzo.cloud.infrastructure.toMultiValue

class MeshApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "https://api.hanzo.ai")
        }
    }

    /**
     * GET /v1/mesh/services
     * Returns the Zero Trust edge services the caller&#39;s org owns.
     * Returns the Zero Trust edge services the caller&#39;s org owns.  One row per real ZT edge service tagged with the org&#39;s \&quot;org-&lt;org&gt;\&quot; role attribute: mtls is \&quot;required\&quot; when the service mandates end-to-end encryption and \&quot;enabled\&quot; otherwise (the fabric always mutually authenticates every link), and status is \&quot;active\&quot; because a listed service is a configured, dialable entry. A service tagged for another org, or tagged for none, is invisible here.  Unlike the network and router reads this does NOT degrade: an unconfigured deployment answers 503 and an unreachable controller surfaces the upstream&#39;s status, so a mesh page never renders \&quot;no services\&quot; for a fabric it simply could not read.
     * @return MeshServiceList
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getMeshServices() : MeshServiceList {
        val localVarResponse = getMeshServicesWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MeshServiceList
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/mesh/services
     * Returns the Zero Trust edge services the caller&#39;s org owns.
     * Returns the Zero Trust edge services the caller&#39;s org owns.  One row per real ZT edge service tagged with the org&#39;s \&quot;org-&lt;org&gt;\&quot; role attribute: mtls is \&quot;required\&quot; when the service mandates end-to-end encryption and \&quot;enabled\&quot; otherwise (the fabric always mutually authenticates every link), and status is \&quot;active\&quot; because a listed service is a configured, dialable entry. A service tagged for another org, or tagged for none, is invisible here.  Unlike the network and router reads this does NOT degrade: an unconfigured deployment answers 503 and an unreachable controller surfaces the upstream&#39;s status, so a mesh page never renders \&quot;no services\&quot; for a fabric it simply could not read.
     * @return ApiResponse<MeshServiceList?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getMeshServicesWithHttpInfo() : ApiResponse<MeshServiceList?> {
        val localVariableConfig = getMeshServicesRequestConfig()

        return request<Unit, MeshServiceList>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getMeshServices
     *
     * @return RequestConfig
     */
    fun getMeshServicesRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/mesh/services",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
