/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param kind 
 * @param actor Defaults to the validated principal (org/sub).
 * @param payload 
 */


data class AgentsEventRequest (

    @SerializedName("kind")
    val kind: AgentsEventRequest.Kind,

    /* Defaults to the validated principal (org/sub). */
    @SerializedName("actor")
    val actor: kotlin.String? = null,

    @SerializedName("payload")
    val payload: kotlin.Any? = null

) {

    /**
     * 
     *
     * Values: message,toolMinusCall,spawn,log,status,control
     */
    enum class Kind(val value: kotlin.String) {
        @SerializedName(value = "message") message("message"),
        @SerializedName(value = "tool-call") toolMinusCall("tool-call"),
        @SerializedName(value = "spawn") spawn("spawn"),
        @SerializedName(value = "log") log("log"),
        @SerializedName(value = "status") status("status"),
        @SerializedName(value = "control") control("control");
    }

}

