/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param model 
 * @param messages 
 * @param maxTokens 
 * @param stream 
 * @param system 
 * @param temperature 
 * @param tools 
 */


data class AiMessageRequest (

    @SerializedName("model")
    val model: kotlin.String,

    @SerializedName("messages")
    val messages: kotlin.collections.List<kotlin.Any>,

    @SerializedName("max_tokens")
    val maxTokens: kotlin.Int,

    @SerializedName("stream")
    val stream: kotlin.Boolean? = false,

    @SerializedName("system")
    val system: kotlin.Any? = null,

    @SerializedName("temperature")
    val temperature: java.math.BigDecimal? = null,

    @SerializedName("tools")
    val tools: kotlin.collections.List<kotlin.Any>? = null

) {


}

