/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model

import ai.hanzo.cloud.model.AiResponsesInputDetails
import ai.hanzo.cloud.model.AiResponsesOutputDetails

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param inputTokens 
 * @param inputTokensDetails 
 * @param outputTokens 
 * @param outputTokensDetails 
 * @param totalTokens 
 */


data class AiResponsesUsage (

    @SerializedName("input_tokens")
    val inputTokens: kotlin.Int? = null,

    @SerializedName("input_tokens_details")
    val inputTokensDetails: AiResponsesInputDetails? = null,

    @SerializedName("output_tokens")
    val outputTokens: kotlin.Int? = null,

    @SerializedName("output_tokens_details")
    val outputTokensDetails: AiResponsesOutputDetails? = null,

    @SerializedName("total_tokens")
    val totalTokens: kotlin.Int? = null

) {


}

