/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param model 
 * @param input 
 * @param voice 
 * @param responseFormat 
 * @param speed 
 */


data class AiSpeechRequest (

    @SerializedName("model")
    val model: kotlin.String,

    @SerializedName("input")
    val input: kotlin.String,

    @SerializedName("voice")
    val voice: kotlin.String,

    @SerializedName("response_format")
    val responseFormat: AiSpeechRequest.ResponseFormat? = null,

    @SerializedName("speed")
    val speed: java.math.BigDecimal? = null

) {

    /**
     * 
     *
     * Values: mp3,opus,aac,flac,wav,pcm
     */
    enum class ResponseFormat(val value: kotlin.String) {
        @SerializedName(value = "mp3") mp3("mp3"),
        @SerializedName(value = "opus") opus("opus"),
        @SerializedName(value = "aac") aac("aac"),
        @SerializedName(value = "flac") flac("flac"),
        @SerializedName(value = "wav") wav("wav"),
        @SerializedName(value = "pcm") pcm("pcm");
    }

}

