/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param events 
 * @param models 
 */


data class AiTaskStats (

    @SerializedName("events")
    val events: kotlin.Int? = null,

    @SerializedName("models")
    val models: kotlin.collections.Map<kotlin.String, kotlin.Int>? = null

) {


}

