/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param username 
 * @param password 
 * @param role 
 */


data class AnalyticsUpdateUserRequest (

    @SerializedName("username")
    val username: kotlin.String,

    @SerializedName("password")
    val password: kotlin.String? = null,

    @SerializedName("role")
    val role: AnalyticsUpdateUserRequest.Role? = null

) {

    /**
     * 
     *
     * Values: admin,user,viewMinusOnly
     */
    enum class Role(val value: kotlin.String) {
        @SerializedName(value = "admin") admin("admin"),
        @SerializedName(value = "user") user("user"),
        @SerializedName(value = "view-only") viewMinusOnly("view-only");
    }

}

