/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model

import ai.hanzo.cloud.model.AnalyticsStatValue

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param pageviews 
 * @param visitors 
 * @param visits 
 * @param bounces 
 * @param totalTime 
 */


data class AnalyticsGetWebsiteStats200Response (

    @SerializedName("pageviews")
    val pageviews: AnalyticsStatValue? = null,

    @SerializedName("visitors")
    val visitors: AnalyticsStatValue? = null,

    @SerializedName("visits")
    val visits: AnalyticsStatValue? = null,

    @SerializedName("bounces")
    val bounces: AnalyticsStatValue? = null,

    @SerializedName("totalTime")
    val totalTime: AnalyticsStatValue? = null

) {


}

