/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model


import com.google.gson.annotations.SerializedName

/**
 * Enforcement decision, echoing the evaluated tuple.
 *
 * @param allow Whether the tuple is permitted by the org's policy set.
 * @param sub 
 * @param obj 
 * @param act 
 */


data class AuthzCheckResponse (

    /* Whether the tuple is permitted by the org's policy set. */
    @SerializedName("allow")
    val allow: kotlin.Boolean? = null,

    @SerializedName("sub")
    val sub: kotlin.String? = null,

    @SerializedName("obj")
    val obj: kotlin.String? = null,

    @SerializedName("act")
    val act: kotlin.String? = null

) {


}

