/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param name 
 * @param displayName 
 * @param type 
 * @param required 
 * @param description 
 */


data class AutomationsPropSpec (

    @SerializedName("name")
    val name: kotlin.String? = null,

    @SerializedName("displayName")
    val displayName: kotlin.String? = null,

    @SerializedName("type")
    val type: AutomationsPropSpec.Type? = null,

    @SerializedName("required")
    val required: kotlin.Boolean? = null,

    @SerializedName("description")
    val description: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: string,number,boolean,`object`,array
     */
    enum class Type(val value: kotlin.String) {
        @SerializedName(value = "string") string("string"),
        @SerializedName(value = "number") number("number"),
        @SerializedName(value = "boolean") boolean("boolean"),
        @SerializedName(value = "object") `object`("object"),
        @SerializedName(value = "array") array("array");
    }

}

