/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param agent 
 * @param from 
 * @param record Record is a per-call flag rather than a product. Where a recording lands and how long it is kept is the org's retention policy, not this call's.
 * @param to 
 * @param webhook 
 */


data class CallInput (

    @SerializedName("agent")
    val agent: kotlin.String? = null,

    @SerializedName("from")
    val from: kotlin.String? = null,

    /* Record is a per-call flag rather than a product. Where a recording lands and how long it is kept is the org's retention policy, not this call's. */
    @SerializedName("record")
    val record: kotlin.Boolean? = null,

    @SerializedName("to")
    val to: kotlin.String? = null,

    @SerializedName("webhook")
    val webhook: kotlin.String? = null

) {


}

