/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param code Code is the referral code the referral was recorded against.
 * @param created Created is true when this call recorded the referral and false when it found one already recorded for this referee — the idempotent replay.
 * @param createdAt CreatedAt is when the referral was first recorded, as a Unix timestamp.
 * @param id ID is the referral's handle.
 * @param status Status is the referral's lifecycle state: \"signup\" until the referee makes metered spend, then \"qualified\", then \"credited\".
 */


data class ClaimView (

    /* Code is the referral code the referral was recorded against. */
    @SerializedName("code")
    val code: kotlin.String? = null,

    /* Created is true when this call recorded the referral and false when it found one already recorded for this referee — the idempotent replay. */
    @SerializedName("created")
    val created: kotlin.Boolean? = null,

    /* CreatedAt is when the referral was first recorded, as a Unix timestamp. */
    @SerializedName("createdAt")
    val createdAt: kotlin.Int? = null,

    /* ID is the referral's handle. */
    @SerializedName("id")
    val id: kotlin.String? = null,

    /* Status is the referral's lifecycle state: \"signup\" until the referee makes metered spend, then \"qualified\", then \"credited\". */
    @SerializedName("status")
    val status: kotlin.String? = null

) {


}

