/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param name Name is the bucket name to create.
 */


data class CloudBucketCreateIn (

    /* Name is the bucket name to create. */
    @SerializedName("name")
    val name: kotlin.String? = null

) {


}

