/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model

import ai.hanzo.cloud.model.CloudDigitaloceanSnapshot

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param `data` 
 * @param msg 
 * @param status 
 */


data class CloudVolumeSnapshotOut (

    @SerializedName("data")
    val `data`: CloudDigitaloceanSnapshot? = null,

    @SerializedName("msg")
    val msg: kotlin.String? = null,

    @SerializedName("status")
    val status: kotlin.String? = null

) {


}

