/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model

import ai.hanzo.cloud.model.CloudDocType

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param `data` Data is every DocType defined in the caller's org.
 */


data class CloudDocTypeList (

    /* Data is every DocType defined in the caller's org. */
    @SerializedName("data")
    val `data`: kotlin.collections.List<CloudDocType>? = null

) {


}

