/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param assignee Assignee is who owns the issue, at most 256 characters. Empty unassigns it.
 * @param description Description is the issue body, at most 32768 characters.
 * @param key Key is the issue's project, from the path.
 * @param labels Labels REPLACES the issue's labels with exactly this set. Each label is at most 48 characters and may not contain a comma (the storage separator); empty entries are dropped.
 * @param num Num is the issue's number within that project, from the path.
 * @param priority Priority is none, urgent, high, medium or low. Empty resets it to none.
 * @param status Status moves the issue between board columns: backlog, todo, in_progress, done or canceled. Empty resets it to backlog.
 * @param title Title is the issue's one-line summary. Non-empty, at most 512 characters.
 */


data class CloudIssuePatch (

    /* Assignee is who owns the issue, at most 256 characters. Empty unassigns it. */
    @SerializedName("assignee")
    val assignee: kotlin.String? = null,

    /* Description is the issue body, at most 32768 characters. */
    @SerializedName("description")
    val description: kotlin.String? = null,

    /* Key is the issue's project, from the path. */
    @SerializedName("key")
    val key: kotlin.String? = null,

    /* Labels REPLACES the issue's labels with exactly this set. Each label is at most 48 characters and may not contain a comma (the storage separator); empty entries are dropped. */
    @SerializedName("labels")
    val labels: kotlin.collections.List<kotlin.String>? = null,

    /* Num is the issue's number within that project, from the path. */
    @SerializedName("num")
    val num: kotlin.Int? = null,

    /* Priority is none, urgent, high, medium or low. Empty resets it to none. */
    @SerializedName("priority")
    val priority: kotlin.String? = null,

    /* Status moves the issue between board columns: backlog, todo, in_progress, done or canceled. Empty resets it to backlog. */
    @SerializedName("status")
    val status: kotlin.String? = null,

    /* Title is the issue's one-line summary. Non-empty, at most 512 characters. */
    @SerializedName("title")
    val title: kotlin.String? = null

) {


}

