/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param at 
 * @param category 
 * @param mrrDeltaCents 
 * @param org 
 * @param plan 
 * @param type 
 */


data class CloudSaaSEvent (

    @SerializedName("at")
    val at: kotlin.String? = null,

    @SerializedName("category")
    val category: kotlin.String? = null,

    @SerializedName("mrrDeltaCents")
    val mrrDeltaCents: kotlin.Int? = null,

    @SerializedName("org")
    val org: kotlin.String? = null,

    @SerializedName("plan")
    val plan: kotlin.String? = null,

    @SerializedName("type")
    val type: kotlin.String? = null

) {


}

