/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param createdAt CreatedAt is when Kubernetes admitted the object, RFC 3339 in UTC.
 * @param name Name is the object's metadata.name, unique within the caller's namespace.
 * @param spec Spec is the resource spec, verbatim as Kubernetes stores it. Present on a single-object read, absent from a list.
 * @param status Status is the live status its operator owns (kserve, trainer or katib), verbatim. Absent until that operator has written one.
 */


data class CloudMlResource (

    /* CreatedAt is when Kubernetes admitted the object, RFC 3339 in UTC. */
    @SerializedName("createdAt")
    val createdAt: kotlin.String? = null,

    /* Name is the object's metadata.name, unique within the caller's namespace. */
    @SerializedName("name")
    val name: kotlin.String? = null,

    /* Spec is the resource spec, verbatim as Kubernetes stores it. Present on a single-object read, absent from a list. */
    @SerializedName("spec")
    val spec: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    /* Status is the live status its operator owns (kserve, trainer or katib), verbatim. Absent until that operator has written one. */
    @SerializedName("status")
    val status: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null

) {


}

