/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param avgValue 
 * @param count 
 * @param ts 
 */


data class CloudAimScorePoint (

    @SerializedName("avgValue")
    val avgValue: java.math.BigDecimal? = null,

    @SerializedName("count")
    val count: kotlin.Int? = null,

    @SerializedName("ts")
    val ts: kotlin.String? = null

) {


}

