/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model

import ai.hanzo.cloud.model.CloudFlowTrigger

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param created 
 * @param displayName 
 * @param flowId 
 * @param id 
 * @param schemaVersion 
 * @param state 
 * @param trigger 
 * @param updated 
 * @param valid 
 */


data class CloudFlowVersion (

    @SerializedName("created")
    val created: kotlin.Int? = null,

    @SerializedName("displayName")
    val displayName: kotlin.String? = null,

    @SerializedName("flowId")
    val flowId: kotlin.String? = null,

    @SerializedName("id")
    val id: kotlin.String? = null,

    @SerializedName("schemaVersion")
    val schemaVersion: kotlin.String? = null,

    @SerializedName("state")
    val state: kotlin.String? = null,

    @SerializedName("trigger")
    val trigger: CloudFlowTrigger? = null,

    @SerializedName("updated")
    val updated: kotlin.Int? = null,

    @SerializedName("valid")
    val valid: kotlin.Boolean? = null

) {


}

