/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param column 
 * @param file 
 * @param function 
 * @param line 
 */


data class CloudFrame (

    @SerializedName("column")
    val column: kotlin.Int? = null,

    @SerializedName("file")
    val file: kotlin.String? = null,

    @SerializedName("function")
    val function: kotlin.String? = null,

    @SerializedName("line")
    val line: kotlin.Int? = null

) {


}

