/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param description Description is the section's blurb, or empty.
 * @param name Name is the section's name, and the value an article's category matches.
 */


data class CloudHelpCategory (

    /* Description is the section's blurb, or empty. */
    @SerializedName("description")
    val description: kotlin.String? = null,

    /* Name is the section's name, and the value an article's category matches. */
    @SerializedName("name")
    val name: kotlin.String? = null

) {


}

