/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param activate Activate switches these tool names on for the caller's org and project.
 * @param deactivate Deactivate switches these tool names off.
 */


data class CloudActivationReq (

    /* Activate switches these tool names on for the caller's org and project. */
    @SerializedName("activate")
    val activate: kotlin.collections.List<kotlin.String>? = null,

    /* Deactivate switches these tool names off. */
    @SerializedName("deactivate")
    val deactivate: kotlin.collections.List<kotlin.String>? = null

) {


}

