/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param createdAt CreatedAt and UpdatedAt are unix seconds, both server-assigned.
 * @param id ID is the server-assigned sequence id (\"seq_\" + 128 random bits).
 * @param name Name is the sequence's label. Required, trimmed, capped at 1024 bytes.
 * @param status Status is the lifecycle: draft, active or archived. Empty means draft, and ONLY an active sequence accepts enrollments.
 * @param updatedAt 
 */


data class CloudSequence (

    /* CreatedAt and UpdatedAt are unix seconds, both server-assigned. */
    @SerializedName("createdAt")
    val createdAt: kotlin.Int? = null,

    /* ID is the server-assigned sequence id (\"seq_\" + 128 random bits). */
    @SerializedName("id")
    val id: kotlin.String? = null,

    /* Name is the sequence's label. Required, trimmed, capped at 1024 bytes. */
    @SerializedName("name")
    val name: kotlin.String? = null,

    /* Status is the lifecycle: draft, active or archived. Empty means draft, and ONLY an active sequence accepts enrollments. */
    @SerializedName("status")
    val status: kotlin.String? = null,

    @SerializedName("updatedAt")
    val updatedAt: kotlin.Int? = null

) {


}

