/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param discard 
 * @param maxAge 
 * @param maxBytes 
 * @param maxMsgs 
 * @param name Name is the stream's name within the org: 1–64 of [A-Za-z0-9_], no dash.
 * @param retention 
 * @param storage 
 * @param subjects 
 */


data class CloudStreamWrite (

    @SerializedName("discard")
    val discard: kotlin.String? = null,

    @SerializedName("maxAge")
    val maxAge: kotlin.Int? = null,

    @SerializedName("maxBytes")
    val maxBytes: kotlin.Int? = null,

    @SerializedName("maxMsgs")
    val maxMsgs: kotlin.Int? = null,

    /* Name is the stream's name within the org: 1–64 of [A-Za-z0-9_], no dash. */
    @SerializedName("name")
    val name: kotlin.String? = null,

    @SerializedName("retention")
    val retention: kotlin.String? = null,

    @SerializedName("storage")
    val storage: kotlin.String? = null,

    @SerializedName("subjects")
    val subjects: kotlin.collections.List<kotlin.String>? = null

) {


}

