/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param repository 
 * @param tag 
 */


data class CloudImageView (

    @SerializedName("repository")
    val repository: kotlin.String? = null,

    @SerializedName("tag")
    val tag: kotlin.String? = null

) {


}

