/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param detail 
 * @param kind 
 * @param label 
 */


data class Completion (

    @SerializedName("detail")
    val detail: kotlin.String? = null,

    @SerializedName("kind")
    val kind: kotlin.Int? = null,

    @SerializedName("label")
    val label: kotlin.String? = null

) {


}

