/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model

import ai.hanzo.cloud.model.DataroomMember

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param createdAt CreatedAt is when the room was created, in unix milliseconds.
 * @param description Description is the room's description, null when none was given.
 * @param documents Documents is every document in the room, in the order a visitor sees them.
 * @param id ID is the room id.
 * @param name Name is the room's display name.
 * @param pId PId is the room's short public identifier.
 * @param updatedAt UpdatedAt is when the room last changed, in unix milliseconds.
 */


data class DataroomRoomDetail (

    /* CreatedAt is when the room was created, in unix milliseconds. */
    @SerializedName("createdAt")
    val createdAt: kotlin.Int? = null,

    /* Description is the room's description, null when none was given. */
    @SerializedName("description")
    val description: kotlin.String? = null,

    /* Documents is every document in the room, in the order a visitor sees them. */
    @SerializedName("documents")
    val documents: kotlin.collections.List<DataroomMember>? = null,

    /* ID is the room id. */
    @SerializedName("id")
    val id: kotlin.String? = null,

    /* Name is the room's display name. */
    @SerializedName("name")
    val name: kotlin.String? = null,

    /* PId is the room's short public identifier. */
    @SerializedName("pId")
    val pId: kotlin.String? = null,

    /* UpdatedAt is when the room last changed, in unix milliseconds. */
    @SerializedName("updatedAt")
    val updatedAt: kotlin.Int? = null

) {


}

