/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param deploymentId DeploymentID is the deployment these logs belong to.
 * @param logs Logs is the recorded status timeline followed by the streamed pod output, newline-separated.
 * @param source Source says which pod the log body carries — `build`, `app`, or `none` when neither pod was reachable — so a console can label the pane honestly.
 */


data class DeployLogs (

    /* DeploymentID is the deployment these logs belong to. */
    @SerializedName("deploymentId")
    val deploymentId: kotlin.String? = null,

    /* Logs is the recorded status timeline followed by the streamed pod output, newline-separated. */
    @SerializedName("logs")
    val logs: kotlin.String? = null,

    /* Source says which pod the log body carries — `build`, `app`, or `none` when neither pod was reachable — so a console can label the pane honestly. */
    @SerializedName("source")
    val source: kotlin.String? = null

) {


}

