/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model

import ai.hanzo.cloud.model.DocumentView

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param disclaimer Disclaimer is the boundary made visible on the wire.
 * @param document Document is the document, rendered content included.
 */


data class DocumentReply (

    /* Disclaimer is the boundary made visible on the wire. */
    @SerializedName("disclaimer")
    val disclaimer: kotlin.String? = null,

    /* Document is the document, rendered content included. */
    @SerializedName("document")
    val document: DocumentView? = null

) {


}

