/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param timestamp 
 * @param eventType 
 * @param level 
 * @param message 
 * @param executionId 
 */


data class EdgeLogEntry (

    @SerializedName("id")
    val id: kotlin.String? = null,

    @SerializedName("timestamp")
    val timestamp: java.time.OffsetDateTime? = null,

    @SerializedName("event_type")
    val eventType: EdgeLogEntry.EventType? = null,

    @SerializedName("level")
    val level: EdgeLogEntry.Level? = null,

    @SerializedName("message")
    val message: kotlin.String? = null,

    @SerializedName("execution_id")
    val executionId: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: uncaughtException,log,boot,beforeUnload
     */
    enum class EventType(val value: kotlin.String) {
        @SerializedName(value = "uncaughtException") uncaughtException("uncaughtException"),
        @SerializedName(value = "log") log("log"),
        @SerializedName(value = "boot") boot("boot"),
        @SerializedName(value = "beforeUnload") beforeUnload("beforeUnload");
    }
    /**
     * 
     *
     * Values: info,warn,error,debug
     */
    enum class Level(val value: kotlin.String) {
        @SerializedName(value = "info") info("info"),
        @SerializedName(value = "warn") warn("warn"),
        @SerializedName(value = "error") error("error"),
        @SerializedName(value = "debug") debug("debug");
    }

}

