/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param createdAt CreatedAt is when it happened, in unix milliseconds.
 * @param `data` 
 * @param email Email is the email of whoever caused it, null for an event with no actor — the sender's own calls are recorded without one.
 * @param id ID is the entry id.
 * @param name Name is the name of whoever caused it, null when it was not recorded.
 * @param type Type is what happened: DOCUMENT_CREATED, RECIPIENT_CREATED, FIELD_CREATED, DOCUMENT_SENT, DOCUMENT_OPENED, DOCUMENT_FIELD_INSERTED, DOCUMENT_RECIPIENT_COMPLETED, DOCUMENT_RECIPIENT_REJECTED or DOCUMENT_COMPLETED.
 */


data class EsignEvent (

    /* CreatedAt is when it happened, in unix milliseconds. */
    @SerializedName("createdAt")
    val createdAt: kotlin.Int? = null,

    @SerializedName("data")
    val `data`: kotlin.Any? = null,

    /* Email is the email of whoever caused it, null for an event with no actor — the sender's own calls are recorded without one. */
    @SerializedName("email")
    val email: kotlin.String? = null,

    /* ID is the entry id. */
    @SerializedName("id")
    val id: kotlin.String? = null,

    /* Name is the name of whoever caused it, null when it was not recorded. */
    @SerializedName("name")
    val name: kotlin.String? = null,

    /* Type is what happened: DOCUMENT_CREATED, RECIPIENT_CREATED, FIELD_CREATED, DOCUMENT_SENT, DOCUMENT_OPENED, DOCUMENT_FIELD_INSERTED, DOCUMENT_RECIPIENT_COMPLETED, DOCUMENT_RECIPIENT_REJECTED or DOCUMENT_COMPLETED. */
    @SerializedName("type")
    val type: kotlin.String? = null

) {


}

