/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model

import ai.hanzo.cloud.model.ExecExecFile

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param files 
 */


data class ExecListSessionFiles200Response (

    @SerializedName("files")
    val files: kotlin.collections.List<ExecExecFile>? = null

) {


}

