/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model

import ai.hanzo.cloud.model.GatewayGetCDNAnalytics200ResponseTimeseriesInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param totalRequests 
 * @param cacheHits 
 * @param cacheMisses 
 * @param hitRatio 
 * @param bandwidthBytes 
 * @param timeseries 
 */


data class GatewayGetCDNAnalytics200Response (

    @SerializedName("total_requests")
    val totalRequests: kotlin.Int? = null,

    @SerializedName("cache_hits")
    val cacheHits: kotlin.Int? = null,

    @SerializedName("cache_misses")
    val cacheMisses: kotlin.Int? = null,

    @SerializedName("hit_ratio")
    val hitRatio: java.math.BigDecimal? = null,

    @SerializedName("bandwidth_bytes")
    val bandwidthBytes: kotlin.Int? = null,

    @SerializedName("timeseries")
    val timeseries: kotlin.collections.List<GatewayGetCDNAnalytics200ResponseTimeseriesInner>? = null

) {


}

