/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param updated Updated is the number of records the grant applied to. Zero is a 404, never a silent no-op.
 */


data class GrantOut (

    /* Updated is the number of records the grant applied to. Zero is a 404, never a silent no-op. */
    @SerializedName("updated")
    val updated: kotlin.Int? = null

) {


}

