/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param from 
 * @param kind parent | link | provenance
 * @param to 
 */


data class GraphEdge (

    @SerializedName("from")
    val from: kotlin.String? = null,

    /* parent | link | provenance */
    @SerializedName("kind")
    val kind: kotlin.String? = null,

    @SerializedName("to")
    val to: kotlin.String? = null

) {


}

