/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param owner 
 * @param name 
 * @param mfaType totp | sms | email | radius | push
 * @param recoveryCodes 
 * @param secret Required for totp; radius/push also require it
 * @param dest Destination for sms/email/radius/push
 */


data class IamControllersMfaSetupEnableForm (

    @SerializedName("owner")
    val owner: kotlin.String,

    @SerializedName("name")
    val name: kotlin.String,

    /* totp | sms | email | radius | push */
    @SerializedName("mfaType")
    val mfaType: kotlin.String,

    @SerializedName("recoveryCodes")
    val recoveryCodes: kotlin.String,

    /* Required for totp; radius/push also require it */
    @SerializedName("secret")
    val secret: kotlin.String? = null,

    /* Destination for sms/email/radius/push */
    @SerializedName("dest")
    val dest: kotlin.String? = null

) {


}

