/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param authorizationEndpoint 
 * @param claimsSupported 
 * @param deviceAuthorizationEndpoint 
 * @param endSessionEndpoint 
 * @param grantTypesSupported 
 * @param idTokenSigningAlgValuesSupported 
 * @param introspectionEndpoint 
 * @param issuer 
 * @param jwksUri 
 * @param requestObjectSigningAlgValuesSupported 
 * @param requestParameterSupported 
 * @param responseModesSupported 
 * @param responseTypesSupported 
 * @param scopesSupported 
 * @param subjectTypesSupported 
 * @param tokenEndpoint 
 * @param userinfoEndpoint 
 */


data class IamObjectOidcDiscovery (

    @SerializedName("authorization_endpoint")
    val authorizationEndpoint: kotlin.String? = null,

    @SerializedName("claims_supported")
    val claimsSupported: kotlin.collections.List<kotlin.String>? = null,

    @SerializedName("device_authorization_endpoint")
    val deviceAuthorizationEndpoint: kotlin.String? = null,

    @SerializedName("end_session_endpoint")
    val endSessionEndpoint: kotlin.String? = null,

    @SerializedName("grant_types_supported")
    val grantTypesSupported: kotlin.collections.List<kotlin.String>? = null,

    @SerializedName("id_token_signing_alg_values_supported")
    val idTokenSigningAlgValuesSupported: kotlin.collections.List<kotlin.String>? = null,

    @SerializedName("introspection_endpoint")
    val introspectionEndpoint: kotlin.String? = null,

    @SerializedName("issuer")
    val issuer: kotlin.String? = null,

    @SerializedName("jwks_uri")
    val jwksUri: kotlin.String? = null,

    @SerializedName("request_object_signing_alg_values_supported")
    val requestObjectSigningAlgValuesSupported: kotlin.collections.List<kotlin.String>? = null,

    @SerializedName("request_parameter_supported")
    val requestParameterSupported: kotlin.Boolean? = null,

    @SerializedName("response_modes_supported")
    val responseModesSupported: kotlin.collections.List<kotlin.String>? = null,

    @SerializedName("response_types_supported")
    val responseTypesSupported: kotlin.collections.List<kotlin.String>? = null,

    @SerializedName("scopes_supported")
    val scopesSupported: kotlin.collections.List<kotlin.String>? = null,

    @SerializedName("subject_types_supported")
    val subjectTypesSupported: kotlin.collections.List<kotlin.String>? = null,

    @SerializedName("token_endpoint")
    val tokenEndpoint: kotlin.String? = null,

    @SerializedName("userinfo_endpoint")
    val userinfoEndpoint: kotlin.String? = null

) {


}

