/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param propertyValues 
 * @param length 
 */


data class KvListRange200Response (

    @SerializedName("values")
    val propertyValues: kotlin.collections.List<kotlin.String>? = null,

    @SerializedName("length")
    val length: kotlin.Int? = null

) {


}

