/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model

import ai.hanzo.cloud.model.MCPServer

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param servers Servers is every external MCP server this org has registered. No secret VALUE is ever included — only whether one is set.
 */


data class McpServerList (

    /* Servers is every external MCP server this org has registered. No secret VALUE is ever included — only whether one is set. */
    @SerializedName("servers")
    val servers: kotlin.collections.List<MCPServer>? = null

) {


}

