/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param name 
 * @param uri 
 * @param propertySize 
 */


data class MlPipelineRunArtifactsInner (

    @SerializedName("name")
    val name: kotlin.String? = null,

    @SerializedName("uri")
    val uri: java.net.URI? = null,

    @SerializedName("size")
    val propertySize: kotlin.Int? = null

) {


}

