/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param body Body is the message text, sent verbatim when present — the no-template path.
 * @param channel Channel selects the delivery channel, sms or email. The per-channel routes (/send/sms, /send/email) pin it, overriding whatever the body names; on the generic route it is required.
 * @param event Event is the event name, which doubles as the template id when TemplateID is empty — the IAM OTP path sends event=iam.otp_sent and nothing else.
 * @param provider Provider pins a provider service name (twilio, plivo, twilio_email, mail). Empty picks the one whose org credentials are actually configured in KMS.
 * @param subject Subject is the message subject, carried on the email channel only.
 * @param sync Sync must be exactly \"true\": delivery here is synchronous, and anything else answers 503 because the queue plane that would run an async dispatch is owned elsewhere. Over REST it rides as ?sync=true (the URL binds over the body); a by-name call states it in its arguments.
 * @param templateId TemplateID selects a built-in template when Body is empty.
 * @param templateVars 
 * @param to To is the destination address per recipient — a phone number for sms, an email address for email. Several recipients fan out into one provider call each, and the response shape follows the count (see the items field).
 */


data class NotifySend (

    /* Body is the message text, sent verbatim when present — the no-template path. */
    @SerializedName("body")
    val body: kotlin.String? = null,

    /* Channel selects the delivery channel, sms or email. The per-channel routes (/send/sms, /send/email) pin it, overriding whatever the body names; on the generic route it is required. */
    @SerializedName("channel")
    val channel: kotlin.String? = null,

    /* Event is the event name, which doubles as the template id when TemplateID is empty — the IAM OTP path sends event=iam.otp_sent and nothing else. */
    @SerializedName("event")
    val event: kotlin.String? = null,

    /* Provider pins a provider service name (twilio, plivo, twilio_email, mail). Empty picks the one whose org credentials are actually configured in KMS. */
    @SerializedName("provider")
    val provider: kotlin.String? = null,

    /* Subject is the message subject, carried on the email channel only. */
    @SerializedName("subject")
    val subject: kotlin.String? = null,

    /* Sync must be exactly \"true\": delivery here is synchronous, and anything else answers 503 because the queue plane that would run an async dispatch is owned elsewhere. Over REST it rides as ?sync=true (the URL binds over the body); a by-name call states it in its arguments. */
    @SerializedName("sync")
    val sync: kotlin.String? = null,

    /* TemplateID selects a built-in template when Body is empty. */
    @SerializedName("template_id")
    val templateId: kotlin.String? = null,

    @SerializedName("template_vars")
    val templateVars: kotlin.Any? = null,

    /* To is the destination address per recipient — a phone number for sms, an email address for email. Several recipients fan out into one provider call each, and the response shape follows the count (see the items field). */
    @SerializedName("to")
    val to: kotlin.collections.List<kotlin.String>? = null

) {


}

