/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model

import ai.hanzo.cloud.model.O11yIntegrationConfig
import ai.hanzo.cloud.model.O11yProviderIntegrationConfig

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param accountId Older fields for backward compatibility with existing AWS agents
 * @param cloudAccountId 
 * @param cloudIntegrationId 
 * @param integrationConfigLegacy 
 * @param integrationConfig 
 * @param providerAccountId 
 * @param removedAtLegacy 
 * @param removedAt 
 */


data class O11yGettableAgentCheckIn (

    /* Older fields for backward compatibility with existing AWS agents */
    @SerializedName("account_id")
    val accountId: kotlin.String? = null,

    @SerializedName("cloud_account_id")
    val cloudAccountId: kotlin.String? = null,

    @SerializedName("cloudIntegrationId")
    val cloudIntegrationId: kotlin.String? = null,

    @SerializedName("integration_config")
    val integrationConfigLegacy: O11yIntegrationConfig? = null,

    @SerializedName("integrationConfig")
    val integrationConfig: O11yProviderIntegrationConfig? = null,

    @SerializedName("providerAccountId")
    val providerAccountId: kotlin.String? = null,

    @SerializedName("removed_at")
    val removedAtLegacy: java.time.OffsetDateTime? = null,

    @SerializedName("removedAt")
    val removedAt: java.time.OffsetDateTime? = null

) {


}

