/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model

import ai.hanzo.cloud.model.O11yO11yEventUser
import ai.hanzo.cloud.model.O11yO11yOccurrenceFrame

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param culprit Culprit is where it came from.
 * @param environment Environment is the deployment it happened in.
 * @param eventId EventID is the occurrence's id.
 * @param fingerprint Fingerprint is the grouping key it was bucketed by.
 * @param frames Frames are the stack, innermost first.
 * @param level Level is its severity, e.g. error, warning, info.
 * @param platform Platform is the reporting runtime.
 * @param release Release is the version that produced it.
 * @param serverName ServerName is the host that reported it.
 * @param serviceName ServiceName is the service that reported it.
 * @param spanId SpanID is the span it belonged to.
 * @param tags Tags are the reporter's own key/value labels.
 * @param timestamp Timestamp is when the error happened.
 * @param traceId TraceID is the trace it belonged to.
 * @param transaction Transaction is the operation it happened in.
 * @param type Type is the exception type.
 * @param user User is the affected end-user context, when the reporter attached one.
 * @param `value` Value is the exception value.
 */


data class O11yO11yOccurrence (

    /* Culprit is where it came from. */
    @SerializedName("culprit")
    val culprit: kotlin.String? = null,

    /* Environment is the deployment it happened in. */
    @SerializedName("environment")
    val environment: kotlin.String? = null,

    /* EventID is the occurrence's id. */
    @SerializedName("eventId")
    val eventId: kotlin.String? = null,

    /* Fingerprint is the grouping key it was bucketed by. */
    @SerializedName("fingerprint")
    val fingerprint: kotlin.String? = null,

    /* Frames are the stack, innermost first. */
    @SerializedName("frames")
    val frames: kotlin.collections.List<O11yO11yOccurrenceFrame>? = null,

    /* Level is its severity, e.g. error, warning, info. */
    @SerializedName("level")
    val level: kotlin.String? = null,

    /* Platform is the reporting runtime. */
    @SerializedName("platform")
    val platform: kotlin.String? = null,

    /* Release is the version that produced it. */
    @SerializedName("release")
    val release: kotlin.String? = null,

    /* ServerName is the host that reported it. */
    @SerializedName("serverName")
    val serverName: kotlin.String? = null,

    /* ServiceName is the service that reported it. */
    @SerializedName("serviceName")
    val serviceName: kotlin.String? = null,

    /* SpanID is the span it belonged to. */
    @SerializedName("spanId")
    val spanId: kotlin.String? = null,

    /* Tags are the reporter's own key/value labels. */
    @SerializedName("tags")
    val tags: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    /* Timestamp is when the error happened. */
    @SerializedName("timestamp")
    val timestamp: java.time.OffsetDateTime? = null,

    /* TraceID is the trace it belonged to. */
    @SerializedName("traceId")
    val traceId: kotlin.String? = null,

    /* Transaction is the operation it happened in. */
    @SerializedName("transaction")
    val transaction: kotlin.String? = null,

    /* Type is the exception type. */
    @SerializedName("type")
    val type: kotlin.String? = null,

    /* User is the affected end-user context, when the reporter attached one. */
    @SerializedName("user")
    val user: O11yO11yEventUser? = null,

    /* Value is the exception value. */
    @SerializedName("value")
    val `value`: kotlin.String? = null

) {


}

