/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model

import ai.hanzo.cloud.model.O11yNotifierConfig
import ai.hanzo.cloud.model.O11yTLSConfig
import ai.hanzo.cloud.model.O11yThreadingConfig

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param notifierConfig 
 * @param authIdentity 
 * @param authPassword 
 * @param authPasswordFile 
 * @param authSecret 
 * @param authSecretFile 
 * @param authUsername 
 * @param forceImplicitTls ForceImplicitTLS controls whether to use implicit TLS (direct TLS connection). true: force use of implicit TLS (direct TLS connection) false: force disable implicit TLS (use explicit TLS/STARTTLS if required) nil (default): auto-detect based on port (465=implicit, other=explicit) for backward compatibility
 * @param from 
 * @param headers 
 * @param hello 
 * @param html 
 * @param requireTls 
 * @param smarthost 
 * @param text 
 * @param threading 
 * @param tlsConfig 
 * @param to Email address to notify.
 */


data class O11yEmailConfig (

    @SerializedName("NotifierConfig")
    val notifierConfig: O11yNotifierConfig? = null,

    @SerializedName("auth_identity")
    val authIdentity: kotlin.String? = null,

    @SerializedName("auth_password")
    val authPassword: kotlin.Any? = null,

    @SerializedName("auth_password_file")
    val authPasswordFile: kotlin.String? = null,

    @SerializedName("auth_secret")
    val authSecret: kotlin.Any? = null,

    @SerializedName("auth_secret_file")
    val authSecretFile: kotlin.String? = null,

    @SerializedName("auth_username")
    val authUsername: kotlin.String? = null,

    /* ForceImplicitTLS controls whether to use implicit TLS (direct TLS connection). true: force use of implicit TLS (direct TLS connection) false: force disable implicit TLS (use explicit TLS/STARTTLS if required) nil (default): auto-detect based on port (465=implicit, other=explicit) for backward compatibility */
    @SerializedName("force_implicit_tls")
    val forceImplicitTls: kotlin.Boolean? = null,

    @SerializedName("from")
    val from: kotlin.String? = null,

    @SerializedName("headers")
    val headers: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @SerializedName("hello")
    val hello: kotlin.String? = null,

    @SerializedName("html")
    val html: kotlin.String? = null,

    @SerializedName("require_tls")
    val requireTls: kotlin.Boolean? = null,

    @SerializedName("smarthost")
    val smarthost: kotlin.Any? = null,

    @SerializedName("text")
    val text: kotlin.String? = null,

    @SerializedName("threading")
    val threading: O11yThreadingConfig? = null,

    @SerializedName("tls_config")
    val tlsConfig: O11yTLSConfig? = null,

    /* Email address to notify. */
    @SerializedName("to")
    val to: kotlin.String? = null

) {


}

