/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model

import ai.hanzo.cloud.model.O11yHTTPClientConfig
import ai.hanzo.cloud.model.O11yNotifierConfig

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param notifierConfig 
 * @param httpConfig 
 * @param text 
 * @param title 
 * @param webhookUrl 
 * @param webhookUrlFile 
 */


data class O11yMSTeamsV2Config (

    @SerializedName("NotifierConfig")
    val notifierConfig: O11yNotifierConfig? = null,

    @SerializedName("http_config")
    val httpConfig: O11yHTTPClientConfig? = null,

    @SerializedName("text")
    val text: kotlin.String? = null,

    @SerializedName("title")
    val title: kotlin.String? = null,

    @SerializedName("webhook_url")
    val webhookUrl: kotlin.Any? = null,

    @SerializedName("webhook_url_file")
    val webhookUrlFile: kotlin.String? = null

) {


}

