/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model

import ai.hanzo.cloud.model.PagesDeploymentConfig

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param preview 
 * @param production 
 */


data class PagesDeploymentConfigs (

    @SerializedName("preview")
    val preview: PagesDeploymentConfig? = null,

    @SerializedName("production")
    val production: PagesDeploymentConfig? = null

) {


}

