/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param requestsPerMinute 
 * @param tokensPerMinute 
 * @param freeCredit 
 */


data class PricingSubscriptionPlanLimits (

    @SerializedName("requestsPerMinute")
    val requestsPerMinute: kotlin.Int? = null,

    @SerializedName("tokensPerMinute")
    val tokensPerMinute: kotlin.Int? = null,

    @SerializedName("freeCredit")
    val freeCredit: java.math.BigDecimal? = null

) {


}

