/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model

import ai.hanzo.cloud.model.KindTotal

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param attempts canonical
 * @param attemptsRetained 
 * @param benchmarks 
 * @param byKind 
 * @param costUsd 
 * @param experiments canonical
 * @param experimentsRetained 
 * @param models 
 * @param project 
 * @param projects 
 */


data class ResearchTotals (

    /* canonical */
    @SerializedName("attempts")
    val attempts: kotlin.Int? = null,

    @SerializedName("attempts_retained")
    val attemptsRetained: kotlin.Int? = null,

    @SerializedName("benchmarks")
    val benchmarks: kotlin.Int? = null,

    @SerializedName("by_kind")
    val byKind: kotlin.collections.List<KindTotal>? = null,

    @SerializedName("cost_usd")
    val costUsd: java.math.BigDecimal? = null,

    /* canonical */
    @SerializedName("experiments")
    val experiments: kotlin.Int? = null,

    @SerializedName("experiments_retained")
    val experimentsRetained: kotlin.Int? = null,

    @SerializedName("models")
    val models: kotlin.Int? = null,

    @SerializedName("project")
    val project: kotlin.String? = null,

    @SerializedName("projects")
    val projects: kotlin.Int? = null

) {


}

