/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param live Live turns the model out of shadow. It defaults to FALSE on every call, so going live is always an explicit act and never a side effect of changing a number.  Setting it requires an ADMIN of this organisation. Arming decides whether the model may change an outcome at all — a payment frozen, a grant refused — for every customer this organisation has, which is a governance act rather than a tuning one. Stating the appetite and the sample needs no admin.
 * @param review Review is the share of the stream that may be sent for examination, in (0, 0.5]. The alert threshold is derived from it as a quantile of the scores actually observed, so the level is governed rather than tuned.
 * @param sample Sample is the share of below-the-line events retained for review, in [0, 1]. It is the instrument that measures what the model missed; there are no labels, so nothing else can.
 */


data class RiskAppetiteIn (

    /* Live turns the model out of shadow. It defaults to FALSE on every call, so going live is always an explicit act and never a side effect of changing a number.  Setting it requires an ADMIN of this organisation. Arming decides whether the model may change an outcome at all — a payment frozen, a grant refused — for every customer this organisation has, which is a governance act rather than a tuning one. Stating the appetite and the sample needs no admin. */
    @SerializedName("live")
    val live: kotlin.Boolean? = null,

    /* Review is the share of the stream that may be sent for examination, in (0, 0.5]. The alert threshold is derived from it as a quantile of the scores actually observed, so the level is governed rather than tuned. */
    @SerializedName("review")
    val review: java.math.BigDecimal? = null,

    /* Sample is the share of below-the-line events retained for review, in [0, 1]. It is the instrument that measures what the model missed; there are no labels, so nothing else can. */
    @SerializedName("sample")
    val sample: java.math.BigDecimal? = null

) {


}

