/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param days Days is how much of the organisation's own history to replay, 1 to 400. Zero takes thirty.
 */


data class RiskSearchIn (

    /* Days is how much of the organisation's own history to replay, 1 to 400. Zero takes thirty. */
    @SerializedName("days")
    val days: kotlin.Int? = null

) {


}

