/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id ID is the content digest of the assertion — the id a redelivery of the same fact resolves to.
 * @param refusal Refusal states what was wrong, for the refused.
 * @param status Status is recorded, duplicate or refused.
 */


data class RiskLabelResult (

    /* ID is the content digest of the assertion — the id a redelivery of the same fact resolves to. */
    @SerializedName("id")
    val id: kotlin.String? = null,

    /* Refusal states what was wrong, for the refused. */
    @SerializedName("refusal")
    val refusal: kotlin.String? = null,

    /* Status is recorded, duplicate or refused. */
    @SerializedName("status")
    val status: kotlin.String? = null

) {


}

