/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model

import ai.hanzo.cloud.model.SearchSearchResultFacetStatsValue

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param hits 
 * @param offset 
 * @param limit 
 * @param estimatedTotalHits 
 * @param totalHits 
 * @param totalPages 
 * @param page 
 * @param hitsPerPage 
 * @param processingTimeMs 
 * @param query 
 * @param facetDistribution 
 * @param facetStats 
 * @param semanticHitCount 
 */


data class SearchSearchResult (

    @SerializedName("hits")
    val hits: kotlin.collections.List<kotlin.Any>? = null,

    @SerializedName("offset")
    val offset: kotlin.Int? = null,

    @SerializedName("limit")
    val limit: kotlin.Int? = null,

    @SerializedName("estimatedTotalHits")
    val estimatedTotalHits: kotlin.Int? = null,

    @SerializedName("totalHits")
    val totalHits: kotlin.Int? = null,

    @SerializedName("totalPages")
    val totalPages: kotlin.Int? = null,

    @SerializedName("page")
    val page: kotlin.Int? = null,

    @SerializedName("hitsPerPage")
    val hitsPerPage: kotlin.Int? = null,

    @SerializedName("processingTimeMs")
    val processingTimeMs: kotlin.Int? = null,

    @SerializedName("query")
    val query: kotlin.String? = null,

    @SerializedName("facetDistribution")
    val facetDistribution: kotlin.collections.Map<kotlin.String, kotlin.collections.Map<kotlin.String, kotlin.Int>>? = null,

    @SerializedName("facetStats")
    val facetStats: kotlin.collections.Map<kotlin.String, SearchSearchResultFacetStatsValue>? = null,

    @SerializedName("semanticHitCount")
    val semanticHitCount: kotlin.Int? = null

) {


}

