/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param target 
 * @param mode 
 */


data class SearchStreamLogsRequest (

    @SerializedName("target")
    val target: kotlin.String,

    @SerializedName("mode")
    val mode: SearchStreamLogsRequest.Mode

) {

    /**
     * 
     *
     * Values: human,json,profile
     */
    enum class Mode(val value: kotlin.String) {
        @SerializedName(value = "human") human("human"),
        @SerializedName(value = "json") json("json"),
        @SerializedName(value = "profile") profile("profile");
    }

}

