/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param keywords Keywords are the seeds. At least one; blanks are dropped.
 * @param language Language is the ISO code. Defaults to \"en\".
 * @param limit Limit is how many phrases to return, 1 to 1000. Defaults to 100. It is what this call is priced on, because the upstream charges per row.
 * @param location Location is the market, as the upstream's numeric code. Defaults to 2840.
 */


data class SeoIdeaIn (

    /* Keywords are the seeds. At least one; blanks are dropped. */
    @SerializedName("keywords")
    val keywords: kotlin.collections.List<kotlin.String>? = null,

    /* Language is the ISO code. Defaults to \"en\". */
    @SerializedName("language")
    val language: kotlin.String? = null,

    /* Limit is how many phrases to return, 1 to 1000. Defaults to 100. It is what this call is priced on, because the upstream charges per row. */
    @SerializedName("limit")
    val limit: kotlin.Int? = null,

    /* Location is the market, as the upstream's numeric code. Defaults to 2840. */
    @SerializedName("location")
    val location: kotlin.Int? = null

) {


}

