/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param subprocessors Subprocessors is the list, each naming at least what it is and what it is for — a name alone says nothing.
 */


data class SubprocessorList (

    /* Subprocessors is the list, each naming at least what it is and what it is for — a name alone says nothing. */
    @SerializedName("subprocessors")
    val subprocessors: kotlin.collections.List<kotlin.Any>? = null

) {


}

