/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model

import ai.hanzo.cloud.model.SourceState
import ai.hanzo.cloud.model.TotalView

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param account Account reports the linked-accounts ledger's own availability, so a partial answer never fabricates this half. It is scoped to the CALLER: the accounts they linked, metered from each provider's own login.
 * @param from From is when the window opens, RFC 3339 UTC. ONE resolver fixes it for both ledgers, so the account rows and the Hanzo rows always cover the same period — two resolvers could drift and turn the union into a lie.
 * @param hanzo Hanzo reports the same for the Hanzo-routed ledger, which is scoped to the ORG rather than the caller — a different question over the same window. The two are independent: either can be unavailable while the other answers, and Rows then carries only the half that did.
 * @param range Range is the resolved period label.
 * @param rows Rows is the union of both ledgers, each row labelled by source and scope — concatenated, NEVER summed: a plan's percentage is not money.
 * @param to To is where the window closes, EXCLUSIVE, RFC 3339 UTC — the instant the read was served. Shared by both ledgers, for the reason From gives.
 */


data class SummaryResp (

    /* Account reports the linked-accounts ledger's own availability, so a partial answer never fabricates this half. It is scoped to the CALLER: the accounts they linked, metered from each provider's own login. */
    @SerializedName("account")
    val account: SourceState? = null,

    /* From is when the window opens, RFC 3339 UTC. ONE resolver fixes it for both ledgers, so the account rows and the Hanzo rows always cover the same period — two resolvers could drift and turn the union into a lie. */
    @SerializedName("from")
    val from: kotlin.String? = null,

    /* Hanzo reports the same for the Hanzo-routed ledger, which is scoped to the ORG rather than the caller — a different question over the same window. The two are independent: either can be unavailable while the other answers, and Rows then carries only the half that did. */
    @SerializedName("hanzo")
    val hanzo: SourceState? = null,

    /* Range is the resolved period label. */
    @SerializedName("range")
    val range: kotlin.String? = null,

    /* Rows is the union of both ledgers, each row labelled by source and scope — concatenated, NEVER summed: a plan's percentage is not money. */
    @SerializedName("rows")
    val rows: kotlin.collections.List<TotalView>? = null,

    /* To is where the window closes, EXCLUSIVE, RFC 3339 UTC — the instant the read was served. Shared by both ledgers, for the reason From gives. */
    @SerializedName("to")
    val to: kotlin.String? = null

) {


}

