/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model

import ai.hanzo.cloud.model.Transaction

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param count 
 * @param transactions 
 * @param user 
 */


data class Transactions (

    @SerializedName("count")
    val count: kotlin.Int? = null,

    @SerializedName("transactions")
    val transactions: kotlin.collections.List<Transaction>? = null,

    @SerializedName("user")
    val user: kotlin.String? = null

) {


}

