/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model

import ai.hanzo.cloud.model.DriftFlag

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param flags 
 * @param severity 
 */


data class Verdict (

    @SerializedName("flags")
    val flags: kotlin.collections.List<DriftFlag>? = null,

    @SerializedName("severity")
    val severity: kotlin.String? = null

) {


}

