/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.hanzo.cloud.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param agentName 
 * @param botVersion 
 */


data class VisorBindAgentRequest (

    @SerializedName("agentName")
    val agentName: kotlin.String,

    @SerializedName("botVersion")
    val botVersion: kotlin.String? = null

) {


}

